// @ts-nocheck
import React, { useState } from 'react';
import { Box, Button, Checkbox, Dialog, DialogActions, DialogContent, DialogTitle, FormControl, FormControlLabel, Grid, IconButton, MenuItem, Paper, Radio, RadioGroup, Select, Stack, Tab, Tabs, TextField, Tooltip, Typography } from '@mui/material';
import { DatePicker } from '@mui/x-date-pickers/DatePicker';
import { Add, Check, Close, ContentCopy, Delete, Description, FilterList, Help, Print, Refresh, Save, Search, Sort, TouchApp, Visibility, ZoomIn } from '@mui/icons-material';
import DataGridWrapper from '../../components/DataGridWrapper';
import MultiDataGridWrapper from '../../components/MultiDataGridWrapper';
import DoubleClickDatePicker from '../../components/DoubleClickDatePicker';
import PageContainer from '../../components/PageContainer';
import { useFrmcust6001PDataConnectionBuildingManageSave } from './useFrmcust6001PDataConnectionBuildingManageSave';
import * as Frmcust6001PDataConnectionBuildingManageSaveData from './Frmcust6001PDataConnectionBuildingManageSaveData';

export const Frmcust6001PDataConnectionBuildingManageSave = () => {
    const hook = useFrmcust6001PDataConnectionBuildingManageSave();
    const [chk_chkBuilding, setChk_chkBuilding] = useState('0');
    const [chk_chkBNM, setChk_chkBNM] = useState('0');
    const [chk_chkAddr, setChk_chkAddr] = useState('0');
    const [chk_chkFireCenter, setChk_chkFireCenter] = useState('0');
    const [chk_chkTel, setChk_chkTel] = useState('0');
    const [chk_chkBiz, setChk_chkBiz] = useState('0');
    const [chk_chkCustomer, setChk_chkCustomer] = useState('0');
    const [chk_chkRegYYMM, setChk_chkRegYYMM] = useState('0');
    const [chk_chkFeeYYMM, setChk_chkFeeYYMM] = useState('0');
    const [chk_chkHopeAddr, setChk_chkHopeAddr] = useState('0');
    const [chk_chkFMNM, setChk_chkFMNM] = useState('0');
    const [chk_chkFMResidentno, setChk_chkFMResidentno] = useState('0');
    const [chk_chkFMStartDate, setChk_chkFMStartDate] = useState('0');
    const [chk_chkFireManager, setChk_chkFireManager] = useState('0');
    const [chk_chkPersonGubun, setChk_chkPersonGubun] = useState('0');
    const [chk_chkRegion, setChk_chkRegion] = useState('0');
    const [chk_chkDetailCourse, setChk_chkDetailCourse] = useState('0');
    const [chk_chkCourse, setChk_chkCourse] = useState('0');
    const [chk_chkoldBuildingEndProc, setChk_chkoldBuildingEndProc] = useState('0');
    const [chk_chkAgencyYn, setChk_chkAgencyYn] = useState('0');
    const [chk_chkPostPlace, setChk_chkPostPlace] = useState('0');
    const [chk_chkHPTEL, setChk_chkHPTEL] = useState('0');
    const columns_gdFPISFireManager = [
        { field: 'SEL', headerName: '', width: 21 },
        { field: 'NM', headerName: '선임자명', width: 78 },
        { field: 'BIRTHDAY', headerName: '생년월일', width: 115 },
        { field: 'APNT_DE', headerName: '선임일자', width: 79 },
        { field: 'MANAGE_ENTRPS_VRSC_AT', headerName: '업무대행여부', width: 90 },
        { field: 'MOBLPHON', headerName: '휴대폰', width: 103 },
    ];
    const columns_gdFPISLicense = [
        { field: 'CRQFC_NM', headerName: '자격증명', width: 166 },
        { field: 'CRQFC_NO', headerName: '자격증번호', width: 136 },
        { field: 'DELVRY_DE', headerName: '발급일자', width: 116 },
    ];
    const columns_gdFPISOwner = [
        { field: 'SEL', headerName: '', width: 23 },
        { field: 'PARTCPNTGUBUN', headerName: '관계자구분', width: 163 },
        { field: 'PARTCPNT', headerName: '성명', width: 131 },
        { field: 'TLPHON_NO', headerName: '전화번호', width: 153 },
    ];
    const columns_gdOwner = [
        { field: 'SEL', headerName: '', width: 23 },
        { field: 'OGUBUN', headerName: '관계자구분', width: 163 },
        { field: 'ONM', headerName: '성명', width: 138 },
        { field: 'OTEL', headerName: '전화번호', width: 154 },
    ];
    const columns_gdFPISAgency = [
        { field: 'SEL', headerName: '', width: 23 },
        { field: 'ENTRPSNM', headerName: '업체명', width: 163 },
        { field: 'RPRSNTV', headerName: '대표자', width: 72 },
        { field: 'TELNO', headerName: '전화번호', width: 109 },
        { field: 'ADRES', headerName: '주소', width: 200 },
        { field: 'REGISTNO', headerName: '등록번호', width: 112 },
        { field: 'CNSGNPD_BEGIN_DE', headerName: '위탁시작일', width: 90 },
        { field: 'CNSGNPD_END_DE', headerName: '위탁종료일', width: 90 },
    ];
    const columns_gdAgency = [
        { field: 'SEL', headerName: '', width: 23 },
        { field: 'AGNM', headerName: '업체명', width: 163 },
        { field: 'AGOWNER', headerName: '대표자', width: 72 },
        { field: 'AGTEL', headerName: '전화번호', width: 109 },
        { field: 'ADDR', headerName: '주소', width: 200 },
        { field: 'AGREGNO', headerName: '등록번호', width: 112 },
        { field: 'AGSTARTDATE', headerName: '위탁시작일', width: 90 },
        { field: 'AGENDDATE', headerName: '위탁종료일', width: 90 },
    ];
    return (
        <PageContainer>

            <Stack direction="row" alignItems="center" justifyContent="space-between" mb={2}>
                <Typography variant="h5">데이터연계 일치화관리</Typography>
                <Stack direction="row" spacing={1}>
                    <Button variant="contained" startIcon={<Close />} onClick={hook.lfn_End}>닫기</Button>
<Button variant="contained" startIcon={<Save />} onClick={hook.lfn_Save}>연계처리(저장)</Button>
<Button variant="contained"  onClick={hook.btnFPISInfo_OnClick}>청시스템 상세보기</Button>
<Button variant="contained"  onClick={hook.btnAllChk_OnClick}>청정보 전체선택</Button>

                </Stack>
            </Stack>
<Grid container spacing={2}>

                <Grid item xs={12} md={12}>
                    <Paper sx={{ p: 2, height: '100%' }}>
                        
                        <Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "55px", py: 0.5, width: "100%" }}><Stack direction="row" alignItems="center" spacing={0.5} sx={{ width: '493px', height: '22px', display: 'flex', alignItems: 'center', ml: '8px' }}>
                    <Typography variant="body2" sx={{ minWidth: 80, bgcolor: '#f5f5f5', p: 0.3, borderRadius: 1 }}>대상물명</Typography>
                    <TextField size="small" fullWidth value={hook.ds_ioFPISBuldstaInfo?.OBJ_NM || ''} sx={{ "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" } }} />
                 </Stack><FormControlLabel control={<Checkbox checked={chk_chkCourse === '1'} onChange={(e) => setChk_chkCourse(e.target.checked ? '1' : '0')} />} label="직능" /><Box sx={{ display: hook.isVisible_cbxCourse ? undefined : 'none' }}><FormControl size="small" fullWidth sx={{ width: '124px', height: '22px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiSelect-select": { padding: "4px 6px !important" }, bgcolor: "#fff" }}><Select  displayEmpty><MenuItem value=""><em>선택</em></MenuItem>{ (Frmcust6001PDataConnectionBuildingManageSaveData.ds_ds_oCourse || []).map(opt => <MenuItem key={opt.CD} value={opt.CD}>{opt.DATA}</MenuItem>) }</Select></FormControl></Box><FormControlLabel control={<Checkbox checked={chk_chkDetailCourse === '1'} onChange={(e) => setChk_chkDetailCourse(e.target.checked ? '1' : '0')} />} label="세부직능" /><Box sx={{ display: hook.isVisible_cbxDetailCourse ? undefined : 'none' }}><FormControl size="small" fullWidth sx={{ width: '193px', height: '22px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiSelect-select": { padding: "4px 6px !important" }, bgcolor: "#fff" }}><Select  displayEmpty><MenuItem value=""><em>선택</em></MenuItem>{ (Frmcust6001PDataConnectionBuildingManageSaveData.ds_ds_oDetailCourse || []).map(opt => <MenuItem key={opt.CD} value={opt.CD}>{opt.DATA}</MenuItem>) }</Select></FormControl></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Stack direction="row" alignItems="center" spacing={0.5} sx={{ width: '493px', height: '22px', display: 'flex', alignItems: 'center', ml: '8px' }}>
                    <Typography variant="body2" sx={{ minWidth: 80, bgcolor: '#f5f5f5', p: 0.3, borderRadius: 1 }}>주소</Typography>
                    <TextField size="small" fullWidth value={hook.ds_ioFPISBuldstaInfo?.LEGALDONG_ADRES_NM || ''} sx={{ "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" } }} />
                 </Stack><FormControlLabel control={<Checkbox checked={chk_chkBuilding === '1'} onChange={(e) => setChk_chkBuilding(e.target.checked ? '1' : '0')} />} label=" 대상물정보" /></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_medFPISZipCode ? undefined : 'none' }}><TextField size="small" fullWidth value={hook.ds_ioFPISBuldstaInfo?.ZIP || ''} sx={{ width: '55px', height: '22px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" }, bgcolor: "#fff" }} /></Box><Box sx={{ display: hook.isVisible_edFPISAddr2 ? undefined : 'none' }}><TextField size="small" fullWidth value={hook.ds_ioFPISBuldstaInfo?.LNBR || ''} sx={{ width: '410px', height: '22px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" }, bgcolor: "#fff" }} /></Box><FormControlLabel control={<Checkbox checked={chk_chkBNM === '1'} onChange={(e) => setChk_chkBNM(e.target.checked ? '1' : '0')} />} label="대상물명" /><Box sx={{ display: hook.isVisible_edBNM ? undefined : 'none' }}><TextField size="small" fullWidth value={hook.ds_ioBuildingInfo?.BNM || ''} sx={{ width: '328px', height: '22px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" }, bgcolor: "#fff" }} /></Box><Box sx={{ display: hook.isVisible_btnBuildingSearch ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnBuildingSearch_OnClick} sx={{ width: '79px', height: '24px', whiteSpace: "nowrap" }}>대상물검색</Button></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Stack direction="row" alignItems="center" spacing={0.5} sx={{ width: '493px', height: '22px', display: 'flex', alignItems: 'center', ml: '8px' }}>
                    <Typography variant="body2" sx={{ minWidth: 80, bgcolor: '#f5f5f5', p: 0.3, borderRadius: 1 }}>소방관서</Typography>
                    <TextField size="small" fullWidth value={hook.ds_ioFPISBuldstaInfo?.CMPN119SC_ID || ''} sx={{ "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" } }} />
                 </Stack><Box sx={{ display: hook.isVisible_btnApply ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnApply_OnClick} sx={{ width: '29px', height: '354px', whiteSpace: "nowrap" }}>적용</Button></Box><FormControlLabel control={<Checkbox checked={chk_chkAddr === '1'} onChange={(e) => setChk_chkAddr(e.target.checked ? '1' : '0')} />} label="주소" /><Box sx={{ display: hook.isVisible_cbxAddrGubun ? undefined : 'none' }}><FormControl size="small" fullWidth sx={{ width: '89px', height: '22px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiSelect-select": { padding: "4px 6px !important" }, bgcolor: "#fff" }}><Select value={hook.ds_ioBuildingInfo?.BADDRGUBUN || ''} displayEmpty><MenuItem value=""><em>선택</em></MenuItem>{ (Frmcust6001PDataConnectionBuildingManageSaveData.ds_ds_oAddr || []).map(opt => <MenuItem key={opt.CD} value={opt.CD}>{opt.DATA}</MenuItem>) }</Select></FormControl></Box><Box sx={{ ml: "0px", minWidth: "322px" }}><Box sx={{ display: hook.isVisible_edRoadAddr1 ? undefined : 'none' }}><TextField size="small" fullWidth value={hook.ds_ioBuildingInfo?.BROADADDR1 || ''} sx={{ width: '322px', height: '22px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" }, bgcolor: "#fff" }} /></Box><Box sx={{ display: hook.isVisible_edAddr1 ? undefined : 'none' }}><TextField size="small" fullWidth value={hook.ds_ioBuildingInfo?.BADDR1 || ''} sx={{ width: '322px', height: '22px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" }, bgcolor: "#fff" }} /></Box></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Stack direction="row" alignItems="center" spacing={0.5} sx={{ width: '346px', height: '22px', display: 'flex', alignItems: 'center', ml: '8px' }}>
                    <Typography variant="body2" sx={{ minWidth: 80, bgcolor: '#f5f5f5', p: 0.3, borderRadius: 1 }}>대상구분</Typography>
                    <TextField size="small" fullWidth value={hook.ds_ioFPISBuldstaInfo?.OBJ_SE || ''} sx={{ "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" } }} />
                 </Stack><Stack direction="row" alignItems="center" spacing={0.5} sx={{ width: '143px', height: '22px', display: 'flex', alignItems: 'center', ml: '3px' }}>
                    <Typography variant="body2" sx={{ minWidth: 80, bgcolor: '#f5f5f5', p: 0.3, borderRadius: 1 }}>공공기관여부</Typography>
                    <TextField size="small" fullWidth value={hook.ds_ioFPISBuldstaInfo?.PBLINSTT_AT || ''} sx={{ "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" } }} />
                 </Stack><Box sx={{ ml: "44px", minWidth: "58px" }}><Box sx={{ display: hook.isVisible_medRoadZipCode ? undefined : 'none' }}><TextField size="small" fullWidth value={hook.ds_ioBuildingInfo?.BZIPCD || ''} sx={{ width: '58px', height: '22px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" }, bgcolor: "#fff" }} /></Box><Box sx={{ display: hook.isVisible_medZipCode ? undefined : 'none' }}><TextField size="small" fullWidth value={hook.ds_ioBuildingInfo?.BZIPCD || ''} sx={{ width: '58px', height: '22px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" }, bgcolor: "#fff" }} /></Box></Box><Box sx={{ display: hook.isVisible_btnSearchZipCode1 ? undefined : 'none' }}><Button variant="outlined"  onClick={hook.btnSearchZipCode1_OnClick} size="small" sx={{ minWidth: 26, p: 0.2, width: '22px', height: '24px', whiteSpace: "nowrap" }}><Search fontSize="small" /></Button></Box><Box sx={{ ml: "2px", minWidth: "410px" }}><Box sx={{ display: hook.isVisible_edRoadAddr2 ? undefined : 'none' }}><TextField size="small" fullWidth value={hook.ds_ioBuildingInfo?.BROADADDR2 || ''} sx={{ width: '410px', height: '22px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" }, bgcolor: "#fff" }} /></Box><Box sx={{ display: hook.isVisible_edAddr2 ? undefined : 'none' }}><TextField size="small" fullWidth value={hook.ds_ioBuildingInfo?.BADDR2 || ''} sx={{ width: '410px', height: '22px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" }, bgcolor: "#fff" }} /></Box></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Stack direction="row" alignItems="center" spacing={0.5} sx={{ width: '493px', height: '22px', display: 'flex', alignItems: 'center', ml: '8px' }}>
                    <Typography variant="body2" sx={{ minWidth: 80, bgcolor: '#f5f5f5', p: 0.3, borderRadius: 1 }}>용도</Typography>
                    <TextField size="small" fullWidth value={hook.ds_ioFPISBuldstaInfo?.MAIN_PRPOS || ''} sx={{ "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" } }} />
                 </Stack><FormControlLabel control={<Checkbox checked={chk_chkFireCenter === '1'} onChange={(e) => setChk_chkFireCenter(e.target.checked ? '1' : '0')} />} label="소방관서" /><Box sx={{ display: hook.isVisible_cbxBonbu ? undefined : 'none' }}><FormControl size="small" fullWidth sx={{ width: '80px', height: '22px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiSelect-select": { padding: "4px 6px !important" }, bgcolor: "#fff" }}><Select value={hook.ds_ioBuildingInfo?.BFIREBONBUCD || ''} displayEmpty><MenuItem value=""><em>선택</em></MenuItem>{ (Frmcust6001PDataConnectionBuildingManageSaveData.ds_ds_oFireBonbuCd || []).map(opt => <MenuItem key={opt.CD} value={opt.CD}>{opt.DATA}</MenuItem>) }</Select></FormControl></Box><Box sx={{ display: hook.isVisible_cbxStation ? undefined : 'none' }}><FormControl size="small" fullWidth sx={{ width: '120px', height: '22px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiSelect-select": { padding: "4px 6px !important" }, bgcolor: "#fff" }}><Select value={hook.ds_ioBuildingInfo?.BFIREUPCD || ''} displayEmpty><MenuItem value=""><em>선택</em></MenuItem>{ (Frmcust6001PDataConnectionBuildingManageSaveData.ds_ds_oFireCd || []).map(opt => <MenuItem key={opt.CD} value={opt.CD}>{opt.DATA}</MenuItem>) }</Select></FormControl></Box><Box sx={{ display: hook.isVisible_cbxCenter ? undefined : 'none' }}><FormControl size="small" fullWidth sx={{ width: '212px', height: '22px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiSelect-select": { padding: "4px 6px !important" }, bgcolor: "#fff" }}><Select value={hook.ds_ioBuildingInfo?.BFIRECD || ''} displayEmpty><MenuItem value=""><em>선택</em></MenuItem>{ (Frmcust6001PDataConnectionBuildingManageSaveData.ds_ds_oFireCenterCd || []).map(opt => <MenuItem key={opt.CD} value={opt.CD}>{opt.DATA}</MenuItem>) }</Select></FormControl></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Stack direction="row" alignItems="center" spacing={0.5} sx={{ width: '346px', height: '22px', display: 'flex', alignItems: 'center', ml: '8px' }}>
                    <Typography variant="body2" sx={{ minWidth: 80, bgcolor: '#f5f5f5', p: 0.3, borderRadius: 1 }}>전화번호</Typography>
                    <TextField size="small" fullWidth value={hook.ds_ioFPISBuldstaInfo?.DYTM_TLPHON || ''} sx={{ "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" } }} />
                 </Stack><Stack direction="row" alignItems="center" spacing={0.5} sx={{ width: '143px', height: '22px', display: 'flex', alignItems: 'center', ml: '3px' }}>
                    <Typography variant="body2" sx={{ minWidth: 80, bgcolor: '#f5f5f5', p: 0.3, borderRadius: 1 }}>업무대행여부</Typography>
                    <TextField size="small" fullWidth  sx={{ "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" } }} />
                 </Stack><FormControlLabel control={<Checkbox checked={chk_chkBiz === '1'} onChange={(e) => setChk_chkBiz(e.target.checked ? '1' : '0')} />} label="용도" /><Box sx={{ display: hook.isVisible_cbxBiz ? undefined : 'none' }}><FormControl size="small" fullWidth sx={{ width: '140px', height: '22px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiSelect-select": { padding: "4px 6px !important" }, bgcolor: "#fff" }}><Select value={hook.ds_ioBuildingInfo?.BBIZCD || ''} displayEmpty><MenuItem value=""><em>선택</em></MenuItem>{ (Frmcust6001PDataConnectionBuildingManageSaveData.ds_ds_oBizCd || []).map(opt => <MenuItem key={opt.CD} value={opt.CD}>{opt.DATA}</MenuItem>) }</Select></FormControl></Box><FormControlLabel control={<Checkbox checked={chk_chkTel === '1'} onChange={(e) => setChk_chkTel(e.target.checked ? '1' : '0')} />} label="전화번호" /><Box sx={{ display: hook.isVisible_edTel ? undefined : 'none' }}><TextField size="small" fullWidth value={hook.ds_ioBuildingInfo?.BTEL || ''} sx={{ width: '175px', height: '22px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" }, bgcolor: "#fff" }} /></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "6px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_lbFPISFireManager ? undefined : 'none' }}><Box sx={{ display: "flex", alignItems: "center", width: '110px', height: '22px' }}><Typography variant="body2">선임자정보</Typography></Box></Box><FormControlLabel control={<Checkbox checked={chk_chkCustomer === '1'} onChange={(e) => setChk_chkCustomer(e.target.checked ? '1' : '0')} />} label=" 고객정보" /></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_gdFPISFireManager ? undefined : 'none' }}><Paper sx={{ width: '493px', height: '117px', width: '100%', height: 'auto', minHeight: '117px' }}><DataGridWrapper rows={hook.ds_ioFPISArsonMngrInfo} columns={columns_gdFPISFireManager} /></Paper></Box><FormControlLabel control={<Checkbox checked={chk_chkRegYYMM === '1'} onChange={(e) => setChk_chkRegYYMM(e.target.checked ? '1' : '0')} />} label="등록년월" /><Box sx={{ display: hook.isVisible_medRegYYMM ? undefined : 'none' }}><TextField size="small" fullWidth value={hook.ds_ioCustomerInfo?.CREGISTERYYMM || ''} sx={{ width: '56px', height: '22px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" }, bgcolor: "#fff" }} /></Box><FormControlLabel control={<Checkbox checked={chk_chkFeeYYMM === '1'} onChange={(e) => setChk_chkFeeYYMM(e.target.checked ? '1' : '0')} />} label="회비부과년월" /><Box sx={{ display: hook.isVisible_medFeeYYMM ? undefined : 'none' }}><TextField size="small" fullWidth value={hook.ds_ioCustomerInfo?.CFEEYYMM || ''} sx={{ width: '56px', height: '22px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" }, bgcolor: "#fff" }} /></Box><FormControlLabel control={<Checkbox checked={chk_chkAgencyYn === '1'} onChange={(e) => setChk_chkAgencyYn(e.target.checked ? '1' : '0')} />} label="업무대행" /><Box sx={{ display: hook.isVisible_cbxAgencyYn ? undefined : 'none' }}><FormControl size="small" fullWidth sx={{ width: '80px', height: '22px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiSelect-select": { padding: "4px 6px !important" }, bgcolor: "#fff" }}><Select value={hook.ds_ioCustomerInfo?.CAGGUBUN || ''} displayEmpty><MenuItem value=""><em>선택</em></MenuItem>{ (Frmcust6001PDataConnectionBuildingManageSaveData.ds_ds_oAgencyYn || []).map(opt => <MenuItem key={opt.CD} value={opt.CD}>{opt.DATA}</MenuItem>) }</Select></FormControl></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Stack direction="row" alignItems="center" spacing={0.5} sx={{ width: '242px', height: '22px', display: 'flex', alignItems: 'center', ml: '539px' }}>
                    <Typography variant="body2" sx={{ minWidth: 90, bgcolor: '#f5f5f5', p: 0.3, borderRadius: 1 }}>고객상태</Typography>
                    <FormControl size="small" fullWidth sx={{ "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiSelect-select": { padding: "4px 6px !important" } }}><Select value={hook.ds_ioCustomerInfo?.CSTATUSGUBUN || ''} displayEmpty><MenuItem value=""><em>선택</em></MenuItem>{ (Frmcust6001PDataConnectionBuildingManageSaveData.ds_ds_oCustomerStatus || []).map(opt => <MenuItem key={opt.CD} value={opt.CD}>{opt.DATA}</MenuItem>) }</Select></FormControl>
                 </Stack><FormControlLabel control={<Checkbox checked={chk_chkPersonGubun === '1'} onChange={(e) => setChk_chkPersonGubun(e.target.checked ? '1' : '0')} />} label="인력구분" /><Box sx={{ display: hook.isVisible_cbxPersonGubun ? undefined : 'none' }}><FormControl size="small" fullWidth sx={{ width: '168px', height: '22px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiSelect-select": { padding: "4px 6px !important" }, bgcolor: "#fff" }}><Select value={hook.ds_ioCustomerInfo?.CPERSONGUBUN || ''} displayEmpty><MenuItem value=""><em>선택</em></MenuItem>{ (Frmcust6001PDataConnectionBuildingManageSaveData.ds_ds_oPersonGubun || []).map(opt => <MenuItem key={opt.CD} value={opt.CD}>{opt.DATA}</MenuItem>) }</Select></FormControl></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><FormControlLabel control={<Checkbox checked={chk_chkHopeAddr === '1'} onChange={(e) => setChk_chkHopeAddr(e.target.checked ? '1' : '0')} />} label="청구지주소" /><Box sx={{ display: hook.isVisible_cbxHopeAddrGubun ? undefined : 'none' }}><FormControl size="small" fullWidth sx={{ width: '89px', height: '22px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiSelect-select": { padding: "4px 6px !important" }, bgcolor: "#fff" }}><Select value={hook.ds_ioCustomerInfo?.CFEEADDRGUBUN || ''} displayEmpty><MenuItem value=""><em>선택</em></MenuItem>{ (Frmcust6001PDataConnectionBuildingManageSaveData.ds_ds_oAddr2 || []).map(opt => <MenuItem key={opt.CD} value={opt.CD}>{opt.DATA}</MenuItem>) }</Select></FormControl></Box><Box sx={{ ml: "0px", minWidth: "322px" }}><Box sx={{ display: hook.isVisible_edHopeRoadAddr1 ? undefined : 'none' }}><TextField size="small" fullWidth value={hook.ds_ioCustomerInfo?.CFEEROADADDR1 || ''} sx={{ width: '322px', height: '22px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" }, bgcolor: "#fff" }} /></Box><Box sx={{ display: hook.isVisible_edHopeAddr1 ? undefined : 'none' }}><TextField size="small" fullWidth value={hook.ds_ioCustomerInfo?.CFEEPOSTADDR1 || ''} sx={{ width: '322px', height: '22px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" }, bgcolor: "#fff" }} /></Box></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_lbFPISLicense1 ? undefined : 'none' }}><Box sx={{ display: "flex", alignItems: "center", width: '45px', height: '42px' }}><Typography variant="body2">자격증</Typography></Box></Box><Box sx={{ display: hook.isVisible_gdFPISLicense ? undefined : 'none' }}><Paper sx={{ width: '447px', height: '117px', width: '100%', height: 'auto', minHeight: '117px' }}><DataGridWrapper rows={hook.ds_ioFPISLicenseInfo} columns={columns_gdFPISLicense} /></Paper></Box><Box sx={{ display: hook.isVisible_cbxPostGubun2 ? undefined : 'none' }}><FormControl size="small" fullWidth sx={{ width: '70px', height: '22px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiSelect-select": { padding: "4px 6px !important" }, bgcolor: "#fff" }}><Select value={hook.ds_ioCustomerInfo?.CFEEPOSTGUBUN || ''} displayEmpty><MenuItem value=""><em>선택</em></MenuItem>{ (Frmcust6001PDataConnectionBuildingManageSaveData.ds_ds_oAddrGubun || []).map(opt => <MenuItem key={opt.CD} value={opt.CD}>{opt.DATA}</MenuItem>) }</Select></FormControl></Box><Box sx={{ ml: "3px", minWidth: "58px" }}><Box sx={{ display: hook.isVisible_medHopeRoadZipCode ? undefined : 'none' }}><TextField size="small" fullWidth value={hook.ds_ioCustomerInfo?.CFEEPOSTZIPCD || ''} sx={{ width: '58px', height: '22px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" }, bgcolor: "#fff" }} /></Box><Box sx={{ display: hook.isVisible_medHopeZipCode ? undefined : 'none' }}><TextField size="small" fullWidth value={hook.ds_ioCustomerInfo?.CFEEPOSTZIPCD || ''} sx={{ width: '58px', height: '22px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" }, bgcolor: "#fff" }} /></Box></Box><Box sx={{ display: hook.isVisible_btnSearchZipCode2 ? undefined : 'none' }}><Button variant="outlined"  onClick={hook.btnSearchZipCode2_OnClick} size="small" sx={{ minWidth: 26, p: 0.2, width: '22px', height: '24px', whiteSpace: "nowrap" }}><Search fontSize="small" /></Button></Box><Box sx={{ ml: "4px", minWidth: "322px" }}><Box sx={{ display: hook.isVisible_edHopeRoadAddr2 ? undefined : 'none' }}><TextField size="small" fullWidth value={hook.ds_ioCustomerInfo?.CFEEROADADDR2 || ''} sx={{ width: '322px', height: '22px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" }, bgcolor: "#fff" }} /></Box><Box sx={{ display: hook.isVisible_edHopeAddr2 ? undefined : 'none' }}><TextField size="small" fullWidth value={hook.ds_ioCustomerInfo?.CFEEPOSTADDR2 || ''} sx={{ width: '322px', height: '22px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" }, bgcolor: "#fff" }} /></Box></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><FormControlLabel control={<Checkbox checked={chk_chkPostPlace === '1'} onChange={(e) => setChk_chkPostPlace(e.target.checked ? '1' : '0')} />} label="투입장소" /><Box sx={{ display: hook.isVisible_edPostPlace ? undefined : 'none' }}><TextField size="small" fullWidth value={hook.ds_ioCustomerInfo?.CEDUPOSTPLACE || ''} sx={{ width: '410px', height: '22px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" }, bgcolor: "#fff" }} /></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_lbFPISLicense2 ? undefined : 'none' }}><Box sx={{ display: "flex", alignItems: "center", width: '45px', height: '42px' }}><Typography variant="body2">정보</Typography></Box></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><FormControlLabel control={<Checkbox checked={chk_chkFireManager === '1'} onChange={(e) => setChk_chkFireManager(e.target.checked ? '1' : '0')} />} label=" 선임자정보" /><Stack direction="row" alignItems="center" spacing={0.5} sx={{ width: '156px', height: '17px', display: 'flex', alignItems: 'center', ml: '3px' }}>
                    <Typography variant="body2" sx={{ minWidth: 80, bgcolor: '#f5f5f5', p: 0.3, borderRadius: 1 }}>개인식별번호</Typography>
                    <TextField size="small" fullWidth value={hook.ds_ioManagerInfo?.FMPERSONKEY || ''} sx={{ "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" } }} />
                 </Stack><FormControlLabel control={<Checkbox checked={chk_chkoldBuildingEndProc === '1'} onChange={(e) => setChk_chkoldBuildingEndProc(e.target.checked ? '1' : '0')} />} label="기존 선임대상물 해임처리" /></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "3px", py: 0.5, width: "100%" }}><FormControlLabel control={<Checkbox checked={chk_chkFMNM === '1'} onChange={(e) => setChk_chkFMNM(e.target.checked ? '1' : '0')} />} label="성명" /><Box sx={{ display: hook.isVisible_edFMNM ? undefined : 'none' }}><TextField size="small" fullWidth value={hook.ds_ioManagerInfo?.FMNM || ''} sx={{ width: '108px', height: '22px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" }, bgcolor: "#fff" }} /></Box><FormControlLabel control={<Checkbox checked={chk_chkFMResidentno === '1'} onChange={(e) => setChk_chkFMResidentno(e.target.checked ? '1' : '0')} />} label="주민번호" /><Box sx={{ display: hook.isVisible_medFMResidentno ? undefined : 'none' }}><TextField size="small" fullWidth value={hook.ds_ioManagerInfo?.FMBIRTHDAY || ''} sx={{ width: '108px', height: '22px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" }, bgcolor: "#fff" }} /></Box><Box sx={{ display: hook.isVisible_btnAuthResidentNo ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnAuthResidentNo_OnClick} sx={{ width: '92px', height: '24px', whiteSpace: "nowrap" }}>실명인증</Button></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_lbFPISOwner ? undefined : 'none' }}><Box sx={{ display: "flex", alignItems: "center", width: '110px', height: '22px' }}><Typography variant="body2">관계자정보</Typography></Box></Box><FormControlLabel control={<Checkbox checked={chk_chkHPTEL === '1'} onChange={(e) => setChk_chkHPTEL(e.target.checked ? '1' : '0')} />} label="휴대폰" /><Box sx={{ display: hook.isVisible_edPTel ? undefined : 'none' }}><TextField size="small" fullWidth value={hook.ds_ioManagerInfo?.FMHHPTEL || ''} sx={{ width: '108px', height: '22px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" }, bgcolor: "#fff" }} /></Box><Box sx={{ display: hook.isVisible_btnLicenseList ? undefined : 'none' }}><Button variant="contained" color="secondary"  onClick={hook.btnLicenseList_OnClick} sx={{ width: '118px', height: '24px', whiteSpace: "nowrap" }}>자격·수료정보조회</Button></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_gdFPISOwner ? undefined : 'none' }}><Paper sx={{ width: '493px', height: '117px', width: '100%', height: 'auto', minHeight: '117px' }}><DataGridWrapper rows={hook.ds_ioFPISPartcpntInfo} columns={columns_gdFPISOwner} /></Paper></Box><FormControlLabel control={<Checkbox checked={chk_chkFMStartDate === '1'} onChange={(e) => setChk_chkFMStartDate(e.target.checked ? '1' : '0')} />} label="선임일자" /><Box sx={{ display: hook.isVisible_calFMStartDate ? undefined : 'none' }}><DoubleClickDatePicker sx={{ width: "102px", "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 0px", fontSize: "12px", marginLeft: "-2px" } }} /></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_lbFMEndStatustitle ? undefined : 'none' }}><Box sx={{ display: "flex", alignItems: "center", width: '90px', height: '22px' }}><Typography variant="body2">해임여부</Typography></Box></Box><Stack direction="row" alignItems="center" spacing={0.5} sx={{ width: '128px', height: '22px', display: 'flex', alignItems: 'center', ml: '2px' }}>
                    <Typography variant="body2" sx={{ minWidth: 30, bgcolor: '#f5f5f5', p: 0.3, borderRadius: 1 }}>해임</Typography>
                    <DoubleClickDatePicker sx={{ width: "102px", "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 0px", fontSize: "12px", marginLeft: "-2px" } }} />
                 </Stack></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "4px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_Static0 ? undefined : 'none' }}><Box sx={{ display: "flex", alignItems: "center", width: '110px', height: '22px' }}><Typography variant="body2">관계자정보</Typography></Box></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_gdOwner ? undefined : 'none' }}><Paper sx={{ width: '503px', height: '90px', width: '100%', height: 'auto', minHeight: '90px' }}><DataGridWrapper rows={hook.ds_ioOwnerInfo} columns={columns_gdOwner} /></Paper></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_Static17 ? undefined : 'none' }}><Box sx={{ display: "flex", alignItems: "center", width: '110px', height: '22px' }}><Typography variant="body2">업무대행정보</Typography></Box></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_gdFPISAgency ? undefined : 'none' }}><Paper sx={{ width: '493px', height: '117px', width: '100%', height: 'auto', minHeight: '117px' }}><DataGridWrapper rows={hook.ds_ioFPISEntrpsVrscInfo} columns={columns_gdFPISAgency} /></Paper></Box><Box sx={{ display: hook.isVisible_Static1 ? undefined : 'none' }}><Box sx={{ display: "flex", alignItems: "center", width: '110px', height: '22px' }}><Typography variant="body2">업무대행정보</Typography></Box></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_gdAgency ? undefined : 'none' }}><Paper sx={{ width: '503px', height: '102px', width: '100%', height: 'auto', minHeight: '102px' }}><DataGridWrapper rows={hook.ds_ioAgencyInfo} columns={columns_gdAgency} /></Paper></Box></Stack>

                    </Paper>
                </Grid>
</Grid>

        </PageContainer>
    );
};
export default Frmcust6001PDataConnectionBuildingManageSave;

function CustomTabPanel(props) {
  const { children, value, index, ...other } = props;

  return (
    <div
      role="tabpanel"
      hidden={value !== index}
      id={`simple-tabpanel-${index}`}
      aria-labelledby={`simple-tab-${index}`}
      {...other}
    >
      {value === index && (
        <Box sx={{ p: 3 }}>
          {children}
        </Box>
      )}
    </div>
  );
}