// @ts-nocheck
import React, { useState } from 'react';
import { Box, Button, Checkbox, Dialog, DialogActions, DialogContent, DialogTitle, FormControl, FormControlLabel, Grid, IconButton, MenuItem, Paper, Radio, RadioGroup, Select, Stack, Tab, Tabs, TextField, Tooltip, Typography } from '@mui/material';
import { DatePicker } from '@mui/x-date-pickers/DatePicker';
import { Add, Check, Close, ContentCopy, Delete, Description, FilterList, Help, Print, Refresh, Save, Search, Sort, TouchApp, Visibility, ZoomIn } from '@mui/icons-material';
import DataGridWrapper from '../../components/DataGridWrapper';
import MultiDataGridWrapper from '../../components/MultiDataGridWrapper';
import DoubleClickDatePicker from '../../components/DoubleClickDatePicker';
import PageContainer from '../../components/PageContainer';
import { useFrmspcleduStat0060 } from './useFrmspcleduStat0060';
import * as FrmspcleduStat0060Data from './FrmspcleduStat0060Data';

export const FrmspcleduStat0060 = () => {
    const hook = useFrmspcleduStat0060();
    const [tabValue_TAB_Training, setTabValue_TAB_Training] = useState(0);
    const columns_gdList = [
        { field: 'GTTEAMNM', headerName: '지 부', width: 70 },
        { field: 'col_1', headerName: '구 분', width: 40, renderCell: (params) => <Stack spacing={0} sx={{ height: "100%", justifyContent: "center" }}><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>계</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>정규</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>특별</Box><Box sx={{ height: "20px" }} /></Stack>, sortable: false },
        { field: 'col_2', headerName: '', width: 60, renderCell: (params) => <Stack spacing={0} sx={{ height: "100%", justifyContent: "center" }}><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>교육횟수</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>대상인원</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>결강인원</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>수료인원</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>교육횟수</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>대상인원</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>결강인원</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>수료인원</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>교육횟수</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>대상인원</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>결강인원</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>수료인원</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>교육횟수</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>대상인원</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>결강인원</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>수료인원</Box></Stack>, sortable: false },
        { field: 'LSRCNT', headerName: '총 계', width: 75, renderCell: (params) => <Stack spacing={0} sx={{ height: "100%", justifyContent: "center" }}><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSRCNT}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSDSCNT}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSOUTCNT}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSPASSCNT}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSRCNT_1}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSDSCNT_1}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSOUTCNT_1}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSPASSCNT_1}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSRCNT_2}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSDSCNT_2}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSOUTCNT_2}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSPASSCNT_2}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSRCNT_3}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSDSCNT_3}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSOUTCNT_3}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSPASSCNT_3}</Box></Stack>, sortable: false },
        { field: 'LSRCNT_BANG0', headerName: '방화관리자 공공', width: 75, renderCell: (params) => <Stack spacing={0} sx={{ height: "100%", justifyContent: "center" }}><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSRCNT_BANG0}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSDSCNT_BANG0}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSOUTCNT_BANG0}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSPASSCNT_BANG0}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSRCNT_BANG0_1}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSDSCNT_BANG0_1}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSOUTCNT_BANG0_1}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSPASSCNT_BANG0_1}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSRCNT_BANG0_2}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSDSCNT_BANG0_2}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSOUTCNT_BANG0_2}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSPASSCNT_BANG0_2}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSRCNT_BANG0_3}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSDSCNT_BANG0_3}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSOUTCNT_BANG0_3}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSPASSCNT_BANG0_3}</Box></Stack>, sortable: false },
        { field: 'LSRCNT_BANG1', headerName: '1급', width: 75, renderCell: (params) => <Stack spacing={0} sx={{ height: "100%", justifyContent: "center" }}><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSRCNT_BANG1}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSDSCNT_BANG1}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSOUTCNT_BANG1}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSPASSCNT_BANG1}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSRCNT_BANG1_1}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSDSCNT_BANG1_1}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSOUTCNT_BANG1_1}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSPASSCNT_BANG1_1}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSRCNT_BANG1_2}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSDSCNT_BANG1_2}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSOUTCNT_BANG1_2}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSPASSCNT_BANG1_2}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSRCNT_BANG1_3}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSDSCNT_BANG1_3}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSOUTCNT_BANG1_3}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSPASSCNT_BANG1_3}</Box></Stack>, sortable: false },
        { field: 'LSRCNT_BANG2N', headerName: '2급정규', width: 75, renderCell: (params) => <Stack spacing={0} sx={{ height: "100%", justifyContent: "center" }}><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSRCNT_BANG2N}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSDSCNT_BANG2N}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSOUTCNT_BANG2N}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSPASSCNT_BANG2N}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSRCNT_BANG2N_1}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSDSCNT_BANG2N_1}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSOUTCNT_BANG2N_1}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSPASSCNT_BANG2N_1}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSRCNT_BANG2N_2}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSDSCNT_BANG2N_2}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSOUTCNT_BANG2N_2}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSPASSCNT_BANG2N_2}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSRCNT_BANG2N_3}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSDSCNT_BANG2N_3}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSOUTCNT_BANG2N_3}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSPASSCNT_BANG2N_3}</Box></Stack>, sortable: false },
        { field: 'LSRCNT_BANG2Y', headerName: '2급면제', width: 75, renderCell: (params) => <Stack spacing={0} sx={{ height: "100%", justifyContent: "center" }}><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSRCNT_BANG2Y}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSDSCNT_BANG2Y}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSOUTCNT_BANG2Y}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSPASSCNT_BANG2Y}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSRCNT_BANG2Y_1}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSDSCNT_BANG2Y_1}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSOUTCNT_BANG2Y_1}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSPASSCNT_BANG2Y_1}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSRCNT_BANG2Y_2}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSDSCNT_BANG2Y_2}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSOUTCNT_BANG2Y_2}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSPASSCNT_BANG2Y_2}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSRCNT_BANG2Y_3}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSDSCNT_BANG2Y_3}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSOUTCNT_BANG2Y_3}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSPASSCNT_BANG2Y_3}</Box></Stack>, sortable: false },
        { field: 'LSRCNT_DAN1', headerName: '위험물 안전관리자', width: 75, renderCell: (params) => <Stack spacing={0} sx={{ height: "100%", justifyContent: "center" }}><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSRCNT_DAN1}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSDSCNT_DAN1}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSOUTCNT_DAN1}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSPASSCNT_DAN1}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSRCNT_DAN1_1}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSDSCNT_DAN1_1}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSOUTCNT_DAN1_1}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSPASSCNT_DAN1_1}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSRCNT_DAN1_2}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSDSCNT_DAN1_2}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSOUTCNT_DAN1_2}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSPASSCNT_DAN1_2}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSRCNT_DAN1_3}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSDSCNT_DAN1_3}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSOUTCNT_DAN1_3}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSPASSCNT_DAN1_3}</Box></Stack>, sortable: false },
        { field: 'LSRCNT_DAN2', headerName: '운송자', width: 75, renderCell: (params) => <Stack spacing={0} sx={{ height: "100%", justifyContent: "center" }}><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSRCNT_DAN2}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSDSCNT_DAN2}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSOUTCNT_DAN2}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSPASSCNT_DAN2}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSRCNT_DAN2_1}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSDSCNT_DAN2_1}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSOUTCNT_DAN2_1}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSPASSCNT_DAN2_1}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSRCNT_DAN2_2}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSDSCNT_DAN2_2}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSOUTCNT_DAN2_2}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSPASSCNT_DAN2_2}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSRCNT_DAN2_3}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSDSCNT_DAN2_3}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSOUTCNT_DAN2_3}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSPASSCNT_DAN2_3}</Box></Stack>, sortable: false },
        { field: 'LSRCNT_DAN3', headerName: '통합자', width: 75, renderCell: (params) => <Stack spacing={0} sx={{ height: "100%", justifyContent: "center" }}><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSRCNT_DAN3}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSDSCNT_DAN3}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSOUTCNT_DAN3}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSPASSCNT_DAN3}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSRCNT_DAN3_1}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSDSCNT_DAN3_1}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSOUTCNT_DAN3_1}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSPASSCNT_DAN3_1}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSRCNT_DAN3_2}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSDSCNT_DAN3_2}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSOUTCNT_DAN3_2}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSPASSCNT_DAN3_2}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSRCNT_DAN3_3}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSDSCNT_DAN3_3}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSOUTCNT_DAN3_3}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.LSPASSCNT_DAN3_3}</Box></Stack>, sortable: false },
    ];
    return (
        <PageContainer>

            <Stack direction="row" alignItems="center" justifyContent="space-between" mb={2}>
                <Typography variant="h5">frmspcleduStat0060</Typography>
                <Stack direction="row" spacing={1}>
                    
                </Stack>
            </Stack>
<Grid container spacing={2}>

                <Grid item xs={12} md={12}>
                    <Paper sx={{ p: 2, height: '100%' }}>
                        
                        <Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "49px", py: 0.5, width: "100%" }}><Stack direction="row" alignItems="center" spacing={0.5} sx={{ width: '164px', height: '27px', display: 'flex', alignItems: 'center', ml: '20px' }}>
                    <Typography variant="body2" sx={{ minWidth: 56, bgcolor: '#f5f5f5', p: 0.3, borderRadius: 1 }}>조회일자</Typography>
                    <DoubleClickDatePicker sx={{ width: "102px", "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 0px", fontSize: "12px", marginLeft: "-2px" } }} />
                 </Stack><Stack direction="row" alignItems="center" spacing={0.5} sx={{ width: '126px', height: '27px', display: 'flex', alignItems: 'center', ml: '5px' }}>
                    <Typography variant="body2" sx={{ minWidth: 11, bgcolor: '#f5f5f5', p: 0.3, borderRadius: 1 }}>~</Typography>
                    <DoubleClickDatePicker sx={{ width: "102px", "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 0px", fontSize: "12px", marginLeft: "-2px" } }} />
                 </Stack><Box sx={{ display: hook.isVisible_Button0_2 ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnSearch_OnClick} sx={{ width: '37px', height: '24px', whiteSpace: "nowrap" }}>검색</Button></Box><Box sx={{ display: hook.isVisible_btnExcell ? undefined : 'none' }}><Button variant="contained" color="success"  onClick={hook.btnExcell_OnClick} sx={{ width: '53px', height: '24px', whiteSpace: "nowrap" }}>엑셀</Button></Box><Box sx={{ display: hook.isVisible_btnPrint ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnPrint_OnClick} sx={{ width: '65px', height: '24px', whiteSpace: "nowrap" }}>출력</Button></Box><Box sx={{ display: hook.isVisible_btnPrintChart ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnPrintChart_OnClick} sx={{ width: '55px', height: '24px', whiteSpace: "nowrap" }}>화면인쇄</Button></Box><Box sx={{ display: hook.isVisible_btnPrintWarmun ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnPrintWarmun_OnClick} sx={{ width: '55px', height: '24px', whiteSpace: "nowrap" }}>화면인쇄</Button></Box><Box sx={{ display: hook.isVisible_btnClose ? undefined : 'none' }}><Button variant="contained"   onClick={hook.lfn_End} sx={{ width: '55px', height: '24px', whiteSpace: "nowrap" }}>화면인쇄</Button></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "14px", py: 0.5, width: "100%" }}><Box sx={{ ml: "11px", minWidth: "765px" }}><Box sx={{ display: hook.isVisible_TAB_Training ? undefined : 'none' }}><Box sx={{ width: '760px', height: '725px', width: "100%", height: "auto", minHeight: "725px" }}><Box sx={{ borderBottom: 1, borderColor: "divider" }}><Tabs value={tabValue_TAB_Training} onChange={(e, v) => setTabValue_TAB_Training(v)} aria-label="TAB_Training"><Tab label="    현    황    " /><Tab label="    Chart    " /></Tabs></Box><CustomTabPanel value={tabValue_TAB_Training} index={0}><Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "6px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_gdList ? undefined : 'none' }}><Paper sx={{ width: '744px', height: '692px', width: '100%', height: 'auto', minHeight: '692px' }}><MultiDataGridWrapper rows={hook.ds_TrainingList} columns={columns_gdList} rowHeight={320} headerHeight={40} hideFooter={true} /></Paper></Box></Stack>
</CustomTabPanel><CustomTabPanel value={tabValue_TAB_Training} index={1}><Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_XChart2 ? undefined : 'none' }}><Box sx={{ width: '432px', height: '338px', border: '1px dashed grey' }}>Unknown: XChart</Box></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_XChart0 ? undefined : 'none' }}><Box sx={{ width: '408px', height: '274px', border: '1px dashed grey' }}>Unknown: XChart</Box></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_Button0 ? undefined : 'none' }}><Button variant="contained"    sx={{ width: '50px', height: '22px', whiteSpace: "nowrap" }}>직능</Button></Box><Box sx={{ display: hook.isVisible_cbxBang ? undefined : 'none' }}><FormControl size="small" fullWidth sx={{ width: '97px', height: '22px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiSelect-select": { padding: "4px 6px !important" }, bgcolor: "#fff" }}><Select  displayEmpty><MenuItem value=""><em>선택</em></MenuItem>{ (FrmspcleduStat0060Data.ds_ds_Bang || []).map(opt => <MenuItem key={opt.CD} value={opt.CD}>{opt.DATA}</MenuItem>) }</Select></FormControl></Box><Box sx={{ display: hook.isVisible_Button1 ? undefined : 'none' }}><Button variant="contained"    sx={{ width: '50px', height: '22px', whiteSpace: "nowrap" }}>지부</Button></Box><Box sx={{ display: hook.isVisible_cbxJibu ? undefined : 'none' }}><FormControl size="small" fullWidth sx={{ width: '81px', height: '22px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiSelect-select": { padding: "4px 6px !important" }, bgcolor: "#fff" }}><Select  displayEmpty><MenuItem value=""><em>선택</em></MenuItem>{ (FrmspcleduStat0060Data.ds_ds_Jibu || []).map(opt => <MenuItem key={opt.CD} value={opt.CD}>{opt.DATA}</MenuItem>) }</Select></FormControl></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "183px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_XChart1 ? undefined : 'none' }}><Box sx={{ width: '760px', height: '441px', border: '1px dashed grey' }}>Unknown: XChart</Box></Box></Stack>
</CustomTabPanel></Box></Box><Box sx={{ display: hook.isVisible_Static2 ? undefined : 'none' }}><Box sx={{ display: "flex", alignItems: "center", width: '80px', height: '22px' }}><Typography variant="body2">[단위 : 명]</Typography></Box></Box></Box></Stack>

                    </Paper>
                </Grid>
</Grid>

        </PageContainer>
    );
};
export default FrmspcleduStat0060;

function CustomTabPanel(props) {
  const { children, value, index, ...other } = props;

  return (
    <div
      role="tabpanel"
      hidden={value !== index}
      id={`simple-tabpanel-${index}`}
      aria-labelledby={`simple-tab-${index}`}
      {...other}
    >
      {value === index && (
        <Box sx={{ p: 3 }}>
          {children}
        </Box>
      )}
    </div>
  );
}