// @ts-nocheck
import React, { useState } from 'react';
import { Box, Button, Dialog, DialogActions, DialogContent, DialogTitle, FormControl, FormControlLabel, Grid, IconButton, MenuItem, Paper, Radio, RadioGroup, Select, Stack, Tab, Tabs, TextField, Tooltip, Typography } from '@mui/material';
import { DatePicker } from '@mui/x-date-pickers/DatePicker';
import { Add, Check, Close, ContentCopy, Delete, Description, FilterList, Help, Print, Refresh, Save, Search, Sort, TouchApp, Visibility, ZoomIn } from '@mui/icons-material';
import DataGridWrapper from '../../components/DataGridWrapper';
import PageContainer from '../../components/PageContainer';
import { useFrmtraining0400MExamJubsuManagement } from './useFrmtraining0400MExamJubsuManagement';
import * as Frmtraining0400MExamJubsuManagementData from './Frmtraining0400MExamJubsuManagementData';
import { FrmCOM0100SWorkFormTitle } from '../COM/FrmCOM0100SWorkFormTitle';

export const Frmtraining0400MExamJubsuManagement = () => {
    const hook = useFrmtraining0400MExamJubsuManagement();
    const columns_gdSetlmentHist = [
        { field: 'id', headerName: '순번', width: 35, renderCell: (params) => params.api.getAllRowIds().indexOf(params.id) + 1 },
        { field: 'ESPROCDATE', headerName: '처리일자', width: 77 },
        { field: 'ESSETLMTYN', headerName: '결제', width: 47 },
        { field: 'EARLYGUBUNNAME', headerName: '선수납', width: 47 },
        { field: 'ESGUBUNCDNM', headerName: '결제구분', width: 98 },
        { field: 'ESGUBUNNM', headerName: '결제방법', width: 106 },
        { field: 'ESPROCAMOUNT', headerName: '금액(원)', width: 70 },
        { field: 'ESREPAYREF', headerName: '환불No.', width: 65 },
        { field: 'ESPROCGTMGNM', headerName: '처리지부', width: 73 },
        { field: 'PROCSABUN', headerName: '처리자', width: 73 },
        { field: 'ESJUMUNNO', headerName: '주문번호', width: 94 },
        { field: 'TAXRCPTYN', headerName: '세금계산서발행여부', width: 0 },
        { field: 'ESPOSGTMGNM', headerName: 'POS지부', width: 94 },
        { field: 'ESMGGTMGNM', headerName: '관리지부', width: 94 },
        { field: 'EARLYGUBUN', headerName: '선수납여부', width: 1 },
    ];
    const columns_gdJubsuInfo = [
        { field: 'id', headerName: '순번', width: 35, renderCell: (params) => params.api.getAllRowIds().indexOf(params.id) + 1 },
        { field: 'MGJIBUCD', headerName: '지부', width: 68 },
        { field: 'YEAR', headerName: '년도', width: 36 },
        { field: 'COURSEMUNJECD', headerName: '직능', width: 134 },
        { field: 'EORDER', headerName: '회차', width: 31 },
        { field: 'JUBSUNO', headerName: '접수번호', width: 58 },
        { field: 'PASSDATE', headerName: '합격일자', width: 83 },
        { field: 'LASTSUNAPGUBUN', headerName: '환불여부', width: 59 },
    ];
    const columns_gdOrderHist = [
        { field: 'id', headerName: '순번', width: 35, renderCell: (params) => params.api.getAllRowIds().indexOf(params.id) + 1 },
        { field: 'BEFORJIBU', headerName: '지부', width: 70 },
        { field: 'BEFORORDER', headerName: '회차', width: 50 },
        { field: 'BEFORJUBSUNO', headerName: '접수번호', width: 60 },
        { field: 'AFTERJIBU', headerName: '변경 후', width: 70 },
        { field: 'AFTERORDER', headerName: '회차', width: 50 },
        { field: 'AFTERJUBSUNO', headerName: '접수번호', width: 60 },
        { field: 'EOHPROCDATE', headerName: '처리일자', width: 79 },
        { field: 'LASTSUNAPGUBUN', headerName: '환불여부', width: 60 },
        { field: 'EJHPROCREASON', headerName: '변경사유', width: 200 },
    ];
    return (
        <PageContainer>

            <Stack direction="row" alignItems="center" justifyContent="space-between" mb={2}>
                <Typography variant="h5">기본정보</Typography>
                <Stack direction="row" spacing={1}>
                    <Button variant="contained" startIcon={<Search />} onClick={hook.lfn_Search}>조회</Button>
<Button variant="contained" startIcon={<Save />} onClick={hook.lfn_Delete}>삭제 저장</Button>
<Button variant="contained" startIcon={<Save />} onClick={hook.lfn_Save}>수정 저장</Button>
<Button variant="contained" startIcon={<Add />} onClick={hook.lfn_Cancel}>입력 초기화</Button>
<Button variant="contained" startIcon={<Save />} onClick={hook.lfn_Excel}>엑셀로 저장</Button>
<Button variant="contained" startIcon={<Print />} onClick={hook.lfn_PrintScreen}>화면 출력</Button>
<Button variant="contained" startIcon={<Close />} onClick={hook.lfn_End}>닫기</Button>
<Button variant="contained" startIcon={<Print />} onClick={hook.lfn_Print}>응시원서출력(F9)</Button>

                </Stack>
            </Stack>
<Grid container spacing={2}>

                <Grid item xs={12} md={8}>
                    <Paper sx={{ p: 2, height: '100%' }}>
                        <Typography variant="subtitle2" sx={{ mb: 2, fontWeight: 'bold' }}>Detailed Info</Typography>
                        <Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "57px", py: 0.5, width: "100%" }}><Stack direction="row" alignItems="center" spacing={0.5} sx={{ width: '179px', height: '22px', display: 'flex', alignItems: 'center', ml: '8px' }}>
                    <Typography variant="body2" sx={{ minWidth: 88, bgcolor: '#f5f5f5', p: 0.3, borderRadius: 1 }}>지부</Typography>
                    <FormControl size="small" fullWidth sx={{ "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiSelect-select": { padding: "4px 6px !important" } }}><Select  displayEmpty><MenuItem value=""><em>선택</em></MenuItem>{ (Frmtraining0400MExamJubsuManagementData.ds_ds_oJibu || []).map(opt => <MenuItem key={opt.CD} value={opt.CD}>{opt.DATA}</MenuItem>) }</Select></FormControl>
                 </Stack><Stack direction="row" alignItems="center" spacing={0.5} sx={{ width: '128px', height: '22px', display: 'flex', alignItems: 'center', ml: '5px' }}>
                    <Typography variant="body2" sx={{ minWidth: 88, bgcolor: '#f5f5f5', p: 0.3, borderRadius: 1 }}>년도</Typography>
                    <TextField size="small" fullWidth  sx={{ "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" } }} />
                 </Stack><Box sx={{ display: hook.isVisible_lbPersonNm ? undefined : 'none' }}><Box sx={{ display: "flex", alignItems: "center", width: '88px', height: '22px' }}><Typography variant="body2">성명</Typography></Box></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "3px", py: 0.5, width: "100%" }}><Stack direction="row" alignItems="center" spacing={0.5} sx={{ width: '312px', height: '98px', display: 'flex', alignItems: 'center', ml: '8px' }}>
                    <Typography variant="body2" sx={{ minWidth: 20, bgcolor: '#f5f5f5', p: 0.3, borderRadius: 1 }}>직능</Typography>
                    <FormControl component="fieldset" sx={{ width: "max-content", whiteSpace: "nowrap" }}><RadioGroup row sx={{ flexWrap: "nowrap" }} >{ (Frmtraining0400MExamJubsuManagementData.ds_ds_oCourse || []).map(opt => <FormControlLabel key={opt.CD} value={opt.CD} control={<Radio />} label={opt.DATA} sx={{ whiteSpace: 'nowrap', flexShrink: 0, mr: 2 }} />) }</RadioGroup></FormControl>
                 </Stack><Box sx={{ display: hook.isVisible_lbBIRTHDAY ? undefined : 'none' }}><Box sx={{ display: "flex", alignItems: "center", width: '88px', height: '22px' }}><Typography variant="body2">주민등록번호</Typography></Box></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_lbHpTel ? undefined : 'none' }}><Box sx={{ display: "flex", alignItems: "center", width: '88px', height: '22px' }}><Typography variant="body2">휴대폰</Typography></Box></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "4px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_lbAddr ? undefined : 'none' }}><Box sx={{ display: "flex", alignItems: "center", width: '88px', height: '22px' }}><Typography variant="body2">주소</Typography></Box></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "25px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_lbTel ? undefined : 'none' }}><Box sx={{ display: "flex", alignItems: "center", width: '88px', height: '22px' }}><Typography variant="body2">전화번호</Typography></Box></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Stack direction="row" alignItems="center" spacing={0.5} sx={{ width: '120px', height: '22px', display: 'flex', alignItems: 'center', ml: '8px' }}>
                    <Typography variant="body2" sx={{ minWidth: 88, bgcolor: '#f5f5f5', p: 0.3, borderRadius: 1 }}>회차</Typography>
                    <TextField size="small" fullWidth  sx={{ "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" } }} />
                 </Stack><Box sx={{ display: hook.isVisible_btnSearchExamOrder ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnSearchExamOrder_OnClick} sx={{ width: '92px', height: '24px', whiteSpace: "nowrap" }}>접수가능회차</Button></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_lbExpYn ? undefined : 'none' }}><Box sx={{ display: "flex", alignItems: "center", width: '88px', height: '50px' }}><Typography variant="body2">응시자격구분</Typography></Box></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Stack direction="row" alignItems="center" spacing={0.5} sx={{ width: '142px', height: '22px', display: 'flex', alignItems: 'center', ml: '8px' }}>
                    <Typography variant="body2" sx={{ minWidth: 88, bgcolor: '#f5f5f5', p: 0.3, borderRadius: 1 }}>접수번호</Typography>
                    <TextField size="small" fullWidth  sx={{ "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" } }} />
                 </Stack><Box sx={{ display: hook.isVisible_btnSeqList ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnSeqList_OnClick} sx={{ width: '92px', height: '24px', whiteSpace: "nowrap" }}>접수목록</Button></Box><Box sx={{ display: hook.isVisible_btnUnUseJubsuNo ? undefined : 'none' }}><Button variant="contained"   onClick={hook.lfn_SearchUnUseJubsuNo} sx={{ width: '66px', height: '24px', whiteSpace: "nowrap" }}>빈번호</Button></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "3px", py: 0.5, width: "100%" }}><Stack direction="row" alignItems="center" spacing={0.5} sx={{ width: '142px', height: '22px', display: 'flex', alignItems: 'center', ml: '8px' }}>
                    <Typography variant="body2" sx={{ minWidth: 88, bgcolor: '#f5f5f5', p: 0.3, borderRadius: 1 }}>좌석번호</Typography>
                    <TextField size="small" fullWidth  sx={{ "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" } }} />
                 </Stack><Box sx={{ display: hook.isVisible_btnModifyHistory ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnModifyHistory_OnClick} sx={{ width: '66px', height: '24px', whiteSpace: "nowrap" }}>변경이력</Button></Box><Box sx={{ display: hook.isVisible_btnJubsuHistory ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnJubsuHistory_OnClick} sx={{ width: '66px', height: '24px', whiteSpace: "nowrap" }}>접수이력</Button></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_Static0 ? undefined : 'none' }}><Box sx={{ display: "flex", alignItems: "center", width: '88px', height: '22px' }}><Typography variant="body2">재시험여부</Typography></Box></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_lbExamInfo ? undefined : 'none' }}><Box sx={{ display: "flex", alignItems: "center", width: '36px', height: '70px' }}><Typography variant="body2">회차정보</Typography></Box></Box><Box sx={{ display: hook.isVisible_lbExamInfo1 ? undefined : 'none' }}><Box sx={{ display: "flex", alignItems: "center", width: '272px', height: '24px' }}><Typography variant="body2"></Typography></Box></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_lbChasuGubun ? undefined : 'none' }}><Box sx={{ display: "flex", alignItems: "center", width: '88px', height: '22px' }}><Typography variant="body2">시험차수</Typography></Box></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_lbExamInfo2 ? undefined : 'none' }}><Box sx={{ display: "flex", alignItems: "center", width: '272px', height: '24px' }}><Typography variant="body2"></Typography></Box></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_lbExamInfo3 ? undefined : 'none' }}><Box sx={{ display: "flex", alignItems: "center", width: '272px', height: '24px' }}><Typography variant="body2"></Typography></Box></Box><Box sx={{ display: hook.isVisible_Static3 ? undefined : 'none' }}><Box sx={{ display: "flex", alignItems: "center", width: '88px', height: '22px' }}><Typography variant="body2">민원서류 등록</Typography></Box></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "3px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_lbOrderChange ? undefined : 'none' }}><Box sx={{ display: "flex", alignItems: "center", width: '88px', height: '22px' }}><Typography variant="body2">회차변경</Typography></Box></Box><Box sx={{ display: hook.isVisible_btnExamJubsuModify ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnExamJubsuModify_OnClick} sx={{ width: '85px', height: '24px', whiteSpace: "nowrap" }}>회차변경</Button></Box><Box sx={{ display: hook.isVisible_btnExamCheatingManageLink ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnExamCheatingManageLink_OnClick} sx={{ width: '92px', height: '24px', whiteSpace: "nowrap" }}>부정행위관리</Button></Box><Box sx={{ display: hook.isVisible_lbSetlmt ? undefined : 'none' }}><Box sx={{ display: "flex", alignItems: "center", width: '120px', height: '22px' }}><Typography variant="body2">결제내역</Typography></Box></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Box sx={{ ml: "8px", minWidth: "144px" }}><Box sx={{ display: hook.isVisible_lbPoint ? undefined : 'none' }}><Box sx={{ display: "flex", alignItems: "center", width: '88px', height: '24px' }}><Typography variant="body2">점수</Typography></Box></Box><Stack direction="row" alignItems="center" spacing={0.5} sx={{ width: '144px', height: '24px', display: 'flex', alignItems: 'center', ml: '0px' }}>
                    <Typography variant="body2" sx={{ minWidth: 88, bgcolor: '#f5f5f5', p: 0.3, borderRadius: 1 }}>합격여부</Typography>
                    <TextField size="small" fullWidth  sx={{ "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" } }} />
                 </Stack></Box><Box sx={{ display: hook.isVisible_ed1PassDate ? undefined : 'none' }}><TextField size="small" fullWidth  sx={{ width: '161px', height: '22px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" }, bgcolor: "#fff" }} /></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "3px", py: 0.5, width: "100%" }}><Box sx={{ ml: "8px", minWidth: "144px" }}><Stack direction="row" alignItems="center" spacing={0.5} sx={{ width: '144px', height: '22px', display: 'flex', alignItems: 'center', ml: '0px' }}>
                    <Typography variant="body2" sx={{ minWidth: 88, bgcolor: '#f5f5f5', p: 0.3, borderRadius: 1 }}>1차 점수</Typography>
                    <TextField size="small" fullWidth  sx={{ "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" } }} />
                 </Stack><Box sx={{ display: hook.isVisible_edPoint ? undefined : 'none' }}><TextField size="small" fullWidth  sx={{ width: '52px', height: '22px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" }, bgcolor: "#fff" }} /></Box></Box><Stack direction="row" alignItems="center" spacing={0.5} sx={{ width: '52px', height: '22px', display: 'flex', alignItems: 'center', ml: '3px' }}>
                    <Typography variant="body2" sx={{ minWidth: 15, bgcolor: '#f5f5f5', p: 0.3, borderRadius: 1 }}>1</Typography>
                    <TextField size="small" fullWidth  sx={{ "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" } }} />
                 </Stack><Stack direction="row" alignItems="center" spacing={0.5} sx={{ width: '52px', height: '22px', display: 'flex', alignItems: 'center', ml: '1px' }}>
                    <Typography variant="body2" sx={{ minWidth: 15, bgcolor: '#f5f5f5', p: 0.3, borderRadius: 1 }}>2</Typography>
                    <TextField size="small" fullWidth  sx={{ "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" } }} />
                 </Stack><Stack direction="row" alignItems="center" spacing={0.5} sx={{ width: '52px', height: '22px', display: 'flex', alignItems: 'center', ml: '2px' }}>
                    <Typography variant="body2" sx={{ minWidth: 15, bgcolor: '#f5f5f5', p: 0.3, borderRadius: 1 }}>3</Typography>
                    <TextField size="small" fullWidth  sx={{ "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" } }} />
                 </Stack><Box sx={{ display: hook.isVisible_btnSetlmt ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnSetlmt_OnClick} sx={{ width: '96px', height: '99px', whiteSpace: "nowrap" }}>결제(POS)</Button></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Stack direction="row" alignItems="center" spacing={0.5} sx={{ width: '143px', height: '22px', display: 'flex', alignItems: 'center', ml: '8px' }}>
                    <Typography variant="body2" sx={{ minWidth: 88, bgcolor: '#f5f5f5', p: 0.3, borderRadius: 1 }}>2차 점수</Typography>
                    <TextField size="small" fullWidth  sx={{ "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" } }} />
                 </Stack><Stack direction="row" alignItems="center" spacing={0.5} sx={{ width: '79px', height: '22px', display: 'flex', alignItems: 'center', ml: '3px' }}>
                    <Typography variant="body2" sx={{ minWidth: 36, bgcolor: '#f5f5f5', p: 0.3, borderRadius: 1 }}>1과목</Typography>
                    <TextField size="small" fullWidth  sx={{ "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" } }} />
                 </Stack><Stack direction="row" alignItems="center" spacing={0.5} sx={{ width: '78px', height: '22px', display: 'flex', alignItems: 'center', ml: '3px' }}>
                    <Typography variant="body2" sx={{ minWidth: 36, bgcolor: '#f5f5f5', p: 0.3, borderRadius: 1 }}>2과목</Typography>
                    <TextField size="small" fullWidth  sx={{ "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" } }} />
                 </Stack></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "12px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_btnExamOmrImage ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnExamOmrImage_OnClick} sx={{ width: '92px', height: '24px', whiteSpace: "nowrap" }}>답안지 보기</Button></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "36px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_lbJubsuInfo ? undefined : 'none' }}><Box sx={{ display: "flex", alignItems: "center", width: '120px', height: '22px' }}><Typography variant="body2">개인접수정보</Typography></Box></Box></Stack>

                    </Paper>
                </Grid>

                <Grid item xs={12} md={4}>
                    <Paper sx={{ p: 2, height: '100%' }}>
                        <Typography variant="subtitle2" sx={{ mb: 2, fontWeight: 'bold' }}>List</Typography>
                        <Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "42px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_imgLastestPicture ? undefined : 'none' }}><Box sx={{ width: '87px', height: '107px', border: "1px solid #ddd", display: "flex", alignItems: "center", justifyContent: "center" }}>Image: imgLastestPicture</Box></Box><Box sx={{ display: hook.isVisible_imgPicture ? undefined : 'none' }}><Box sx={{ width: '112px', height: '149px', border: "1px solid #ddd", display: "flex", alignItems: "center", justifyContent: "center" }}>Image: imgPicture</Box></Box><Box sx={{ display: hook.isVisible_radChangeTpmgno ? undefined : 'none' }}><FormControl component="fieldset" sx={{ width: '200px', height: '22px', width: "max-content", whiteSpace: "nowrap", pr: 2 }}><RadioGroup row sx={{ flexWrap: "nowrap" }} >{ (Frmtraining0400MExamJubsuManagementData.ds_ds_oChangeTpmgno || []).map(opt => <FormControlLabel key={opt.CD} value={opt.CD} control={<Radio />} label={opt.DATA} sx={{ whiteSpace: 'nowrap', flexShrink: 0, mr: 2 }} />) }</RadioGroup></FormControl></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_edPersonNm ? undefined : 'none' }}><TextField size="small" fullWidth value={hook.ds_ioExamJubsu?.PERSONNM || ''} sx={{ width: '106px', height: '22px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" }, bgcolor: "#fff" }} /></Box><Box sx={{ display: hook.isVisible_btnSearchPersonInfo ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnSearchPersonInfo_OnClick} sx={{ width: '118px', height: '24px', whiteSpace: "nowrap" }}>접수자  검색</Button></Box><Box sx={{ display: hook.isVisible_Button0 ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnSearchPersonInfoChange_OnClick} sx={{ width: '105px', height: '24px', whiteSpace: "nowrap" }}>접수자정보변경</Button></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_Edit0 ? undefined : 'none' }}><TextField size="small" fullWidth value={hook.ds_ioExamJubsu?.MUNJEGUBUN || ''} sx={{ width: '24px', height: '18px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" }, bgcolor: "#fff" }} /></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_medBIRTHDAY ? undefined : 'none' }}><TextField size="small" fullWidth value={hook.ds_ioExamJubsu?.BIRTHDAY7 || ''} sx={{ width: '106px', height: '22px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" }, bgcolor: "#fff" }} /></Box><Box sx={{ display: hook.isVisible_btnTraingJubsuHist ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnTraingJubsuHist_OnClick} sx={{ width: '118px', height: '24px', whiteSpace: "nowrap" }}>기존접수이력(F6)</Button></Box><Box sx={{ display: hook.isVisible_btnAuthBIRTHDAY ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnAuthBIRTHDAY_OnClick} sx={{ width: '105px', height: '24px', whiteSpace: "nowrap" }}>실명인증</Button></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_edHpTel ? undefined : 'none' }}><TextField size="small" fullWidth value={hook.ds_ioExamJubsu?.HPTEL || ''} sx={{ width: '106px', height: '22px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" }, bgcolor: "#fff" }} /></Box><Box sx={{ display: hook.isVisible_btnSendSms ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnSendSms_OnClick} sx={{ width: '118px', height: '24px', whiteSpace: "nowrap" }}>문자발송</Button></Box><Box sx={{ display: hook.isVisible_btnSmsStat ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnSmsStat_OnClick} sx={{ width: '105px', height: '24px', whiteSpace: "nowrap" }}>문자현황</Button></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_btnPictureManagement ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnPictureManagement_OnClick} sx={{ width: '93px', height: '24px', whiteSpace: "nowrap" }}>사진관리</Button></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_medZipCode ? undefined : 'none' }}><TextField size="small" fullWidth value={hook.ds_ioExamJubsu?.ZIPCD || ''} sx={{ width: '50px', height: '22px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" }, bgcolor: "#fff" }} /></Box><Box sx={{ display: hook.isVisible_btnSearchZipCode ? undefined : 'none' }}><Button variant="outlined"  onClick={hook.btnSearchZipCode_OnClick} size="small" sx={{ minWidth: 26, p: 0.2, width: '22px', height: '24px', whiteSpace: "nowrap" }}><Search fontSize="small" /></Button></Box><Box sx={{ display: hook.isVisible_edAddr1 ? undefined : 'none' }}><TextField size="small" fullWidth value={hook.ds_ioExamJubsu?.ADDR1 || ''} sx={{ width: '268px', height: '22px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" }, bgcolor: "#fff" }} /></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Box sx={{ ml: "332px", minWidth: "438px" }}><Box sx={{ display: hook.isVisible_edAddr2 ? undefined : 'none' }}><TextField size="small" fullWidth value={hook.ds_ioExamJubsu?.ADDR2 || ''} sx={{ width: '436px', height: '22px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" }, bgcolor: "#fff" }} /></Box><Box sx={{ display: hook.isVisible_cbxAddrGubun ? undefined : 'none' }}><FormControl size="small" fullWidth sx={{ width: '89px', height: '22px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiSelect-select": { padding: "4px 6px !important" }, bgcolor: "#fff" }}><Select value={hook.ds_ioExamJubsu?.EJADDRGUBUN || ''} displayEmpty><MenuItem value=""><em>선택</em></MenuItem>{ (Frmtraining0400MExamJubsuManagementData.ds_ds_oAddr || []).map(opt => <MenuItem key={opt.CD} value={opt.CD}>{opt.DATA}</MenuItem>) }</Select></FormControl></Box></Box><Box sx={{ display: hook.isVisible_btnApplyPicture ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnApplyPicture_OnClick} sx={{ width: '92px', height: '24px', whiteSpace: "nowrap" }}>최근사진반영</Button></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_edTel ? undefined : 'none' }}><TextField size="small" fullWidth value={hook.ds_ioExamJubsu?.TEL || ''} sx={{ width: '104px', height: '22px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" }, bgcolor: "#fff" }} /></Box><Box sx={{ display: hook.isVisible_btnSearchRegPicture ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnSearchRegPicture_OnClick} sx={{ width: '93px', height: '24px', whiteSpace: "nowrap" }}>등록사진조회</Button></Box><Box sx={{ display: hook.isVisible_btnScanPicture ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnScanPicture_OnClick} sx={{ width: '105px', height: '24px', whiteSpace: "nowrap" }}>SVP5300사진스캔</Button></Box><Box sx={{ display: hook.isVisible_btnPhotoScan ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnPhotoScan_OnClick} sx={{ width: '95px', height: '24px', whiteSpace: "nowrap" }}>D400사진스캔</Button></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Box sx={{ ml: "424px", minWidth: "563px" }}><Box sx={{ display: hook.isVisible_radJubsuGubun2 ? undefined : 'none' }}><FormControl component="fieldset" sx={{ width: '563px', height: '50px', width: "max-content", whiteSpace: "nowrap", pr: 2 }}><RadioGroup row sx={{ flexWrap: "nowrap" }} >{ (Frmtraining0400MExamJubsuManagementData.ds_ds_ioJubsuGubun2 || []).map(opt => <FormControlLabel key={opt.CD} value={opt.CD} control={<Radio />} label={opt.DATA} sx={{ whiteSpace: 'nowrap', flexShrink: 0, mr: 2 }} />) }</RadioGroup></FormControl></Box><Box sx={{ display: hook.isVisible_radJubsuGubun ? undefined : 'none' }}><FormControl component="fieldset" sx={{ width: '563px', height: '51px', width: "max-content", whiteSpace: "nowrap", pr: 2 }}><RadioGroup row sx={{ flexWrap: "nowrap" }} >{ (Frmtraining0400MExamJubsuManagementData.ds_ds_ioJubsuGubun || []).map(opt => <FormControlLabel key={opt.CD} value={opt.CD} control={<Radio />} label={opt.DATA} sx={{ whiteSpace: 'nowrap', flexShrink: 0, mr: 2 }} />) }</RadioGroup></FormControl></Box><Box sx={{ display: hook.isVisible_cbxCourse ? undefined : 'none' }}><FormControl size="small" fullWidth sx={{ width: '147px', height: '21px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiSelect-select": { padding: "4px 6px !important" }, bgcolor: "#fff" }}><Select  displayEmpty><MenuItem value=""><em>선택</em></MenuItem>{ (Frmtraining0400MExamJubsuManagementData.ds_ds_oJubsuGubunCourse || []).map(opt => <MenuItem key={opt.CD} value={opt.CD}>{opt.DATA}</MenuItem>) }</Select></FormControl></Box></Box><Box sx={{ display: hook.isVisible_btnEmailStat ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnEmailStat_OnClick} sx={{ width: '66px', height: '24px', whiteSpace: "nowrap" }}>메일현황</Button></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_cbxGaJubsuGubun2 ? undefined : 'none' }}><FormControl size="small" fullWidth sx={{ width: '81px', height: '22px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiSelect-select": { padding: "4px 6px !important" }, bgcolor: "#fff" }}><Select value={hook.ds_ioExamJubsu?.EJJUBSUGUBUN2 || ''} displayEmpty><MenuItem value=""><em>선택</em></MenuItem>{ (Frmtraining0400MExamJubsuManagementData.ds_ds_ioGaJubsuGubun2 || []).map(opt => <MenuItem key={opt.CD} value={opt.CD}>{opt.DATA}</MenuItem>) }</Select></FormControl></Box><Box sx={{ display: hook.isVisible_cbxGaJubsuGubun ? undefined : 'none' }}><FormControl size="small" fullWidth sx={{ width: '81px', height: '22px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiSelect-select": { padding: "4px 6px !important" }, bgcolor: "#fff" }}><Select  displayEmpty><MenuItem value=""><em>선택</em></MenuItem>{ (Frmtraining0400MExamJubsuManagementData.ds_ds_ioGaJubsuGubun || []).map(opt => <MenuItem key={opt.CD} value={opt.CD}>{opt.DATA}</MenuItem>) }</Select></FormControl></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Stack direction="row" alignItems="center" spacing={0.5} sx={{ width: '142px', height: '22px', display: 'flex', alignItems: 'center', ml: '1168px' }}>
                    <Typography variant="body2" sx={{ minWidth: 88, bgcolor: '#f5f5f5', p: 0.3, borderRadius: 1 }}> 강습수료횟수</Typography>
                    <TextField size="small" fullWidth  sx={{ "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" } }} />
                 </Stack><Box sx={{ display: hook.isVisible_lbTextBlue ? undefined : 'none' }}><Box sx={{ display: "flex", alignItems: "center", width: '14px', height: '22px' }}><Typography variant="body2">회</Typography></Box></Box><Stack direction="row" alignItems="center" spacing={0.5} sx={{ width: '194px', height: '22px', display: 'flex', alignItems: 'center', ml: '1px' }}>
                    <Typography variant="body2" sx={{ minWidth: 104, bgcolor: '#f5f5f5', p: 0.3, borderRadius: 1 }}> 강습수료일(최종)</Typography>
                    <TextField size="small" fullWidth  sx={{ "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" } }} />
                 </Stack></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_radRejubsuYN ? undefined : 'none' }}><FormControl component="fieldset" sx={{ width: '124px', height: '23px', width: "max-content", whiteSpace: "nowrap", pr: 2 }}><RadioGroup row sx={{ flexWrap: "nowrap" }} value={hook.ds_ioExamJubsu?.EJREJUBSUYN || ''}>{ (Frmtraining0400MExamJubsuManagementData.ds_ds_ioYN || []).map(opt => <FormControlLabel key={opt.CD} value={opt.CD} control={<Radio />} label={opt.DATA} sx={{ whiteSpace: 'nowrap', flexShrink: 0, mr: 2 }} />) }</RadioGroup></FormControl></Box><Box sx={{ ml: "4px", minWidth: "278px" }}><Box sx={{ display: hook.isVisible_Static5 ? undefined : 'none' }}><Box sx={{ display: "flex", alignItems: "center", width: '106px', height: '22px' }}><Typography variant="body2">응시료면제사유</Typography></Box></Box><Box sx={{ display: hook.isVisible_lbReason ? undefined : 'none' }}><Box sx={{ display: "flex", alignItems: "center", width: '106px', height: '22px' }}><Typography variant="body2">학·경력 인정사유</Typography></Box></Box><Stack direction="row" alignItems="center" spacing={0.5} sx={{ width: '277px', height: '23px', display: 'flex', alignItems: 'center', ml: '0px' }}>
                    <Typography variant="body2" sx={{ minWidth: 106, bgcolor: '#f5f5f5', p: 0.3, borderRadius: 1 }}>가접수 인정사유</Typography>
                    <TextField size="small" fullWidth value={hook.ds_ioExamJubsu?.EJJUBSUREMARK || ''} sx={{ "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" } }} />
                 </Stack><Box sx={{ display: hook.isVisible_edReason ? undefined : 'none' }}><TextField size="small" fullWidth value={hook.ds_ioExamJubsu?.EJJUBSUREASON || ''} sx={{ width: '171px', height: '23px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" }, bgcolor: "#fff" }} /></Box><Box sx={{ display: hook.isVisible_edEJJUBSUREASON2 ? undefined : 'none' }}><TextField size="small" fullWidth value={hook.ds_ioExamJubsu?.EJJUBSUREASON2 || ''} sx={{ width: '171px', height: '23px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" }, bgcolor: "#fff" }} /></Box></Box><Box sx={{ display: hook.isVisible_btnLoadScanPicture ? undefined : 'none' }}><Button variant="contained" color="success"  onClick={hook.btnLoadScanPicture_OnClick} sx={{ width: '119px', height: '24px', whiteSpace: "nowrap" }}>스캔사진불러오기</Button></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_radChasuGubun ? undefined : 'none' }}><FormControl component="fieldset" sx={{ width: '332px', height: '22px', width: "max-content", whiteSpace: "nowrap", pr: 2 }}><RadioGroup row sx={{ flexWrap: "nowrap" }} value={hook.ds_ioExamJubsu?.EJCHASUGUBUN || ''}>{ (Frmtraining0400MExamJubsuManagementData.ds_ds_ioChasuGubun || []).map(opt => <FormControlLabel key={opt.CD} value={opt.CD} control={<Radio />} label={opt.DATA} sx={{ whiteSpace: 'nowrap', flexShrink: 0, mr: 2 }} />) }</RadioGroup></FormControl></Box><Box sx={{ display: hook.isVisible_fdImage2 ? undefined : 'none' }}><Button variant="contained" color="success" startIcon={<Description />} sx={{ width: '24px', height: '26px', whiteSpace: "nowrap" }}>fdImage2</Button></Box><Box sx={{ display: hook.isVisible_hfImage2 ? undefined : 'none' }}><Button variant="contained" color="success" startIcon={<Description />} sx={{ width: '24px', height: '26px', whiteSpace: "nowrap" }}>hfImage2</Button></Box><Box sx={{ display: hook.isVisible_fiImageFile2 ? undefined : 'none' }}><Button variant="contained" color="success" startIcon={<Description />} sx={{ width: '24px', height: '26px', whiteSpace: "nowrap" }}>fiImageFile2</Button></Box><Box sx={{ display: hook.isVisible_btnLoadPicture ? undefined : 'none' }}><Button variant="contained" color="success"  onClick={hook.btnLoadPicture_OnClick} sx={{ width: '119px', height: '24px', whiteSpace: "nowrap" }}>사진찾기</Button></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_cbxForm ? undefined : 'none' }}><FormControl size="small" fullWidth sx={{ width: '172px', height: '22px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiSelect-select": { padding: "4px 6px !important" }, bgcolor: "#fff" }}><Select  displayEmpty><MenuItem value=""><em>선택</em></MenuItem>{ (Frmtraining0400MExamJubsuManagementData.ds_ds_oForm || []).map(opt => <MenuItem key={opt.CD} value={opt.CD}>{opt.DATA}</MenuItem>) }</Select></FormControl></Box><Box sx={{ display: hook.isVisible_edFormResult ? undefined : 'none' }}><TextField size="small" fullWidth  sx={{ width: '45px', height: '22px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" }, bgcolor: "#fff" }} /></Box><Box sx={{ display: hook.isVisible_btnSeverFormView ? undefined : 'none' }}><Button variant="outlined"  onClick={hook.btnSeverFormView_OnClick} size="small" sx={{ minWidth: 26, p: 0.2, width: '22px', height: '24px', whiteSpace: "nowrap" }}><Search fontSize="small" /></Button></Box><Box sx={{ display: hook.isVisible_btnScan ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnScan_OnClick} sx={{ width: '66px', height: '24px', whiteSpace: "nowrap" }}>①스캔실행</Button></Box><Box sx={{ display: hook.isVisible_btnScanSearch ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnScanSearch_OnClick} sx={{ width: '66px', height: '24px', whiteSpace: "nowrap" }}>②불러오기</Button></Box><Box sx={{ display: hook.isVisible_edScanFileName ? undefined : 'none' }}><TextField size="small" fullWidth  sx={{ width: '74px', height: '22px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" }, bgcolor: "#fff" }} /></Box><Box sx={{ display: hook.isVisible_btnLocalFormView ? undefined : 'none' }}><Button variant="outlined"  onClick={hook.btnLocalFormView_OnClick} size="small" sx={{ minWidth: 26, p: 0.2, width: '22px', height: '24px', whiteSpace: "nowrap" }}><Search fontSize="small" /></Button></Box><Box sx={{ display: hook.isVisible_btnScanSave ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnScanSave_OnClick} sx={{ width: '66px', height: '24px', whiteSpace: "nowrap" }}>③서류저장</Button></Box><Box sx={{ display: hook.isVisible_btnFormDelete ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnFormDelete_OnClick} sx={{ width: '16px', height: '22px', whiteSpace: "nowrap" }}>서류삭제</Button></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "11px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_btnDeleteSettlement ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnDeleteSettlement_OnClick} sx={{ width: '81px', height: '24px', whiteSpace: "nowrap" }}>결제삭제</Button></Box><Box sx={{ display: hook.isVisible_btnPrintReRctPDF ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnPrintReRctPDF_OnClick} sx={{ width: '80px', height: '24px', whiteSpace: "nowrap" }}>영수증PDF</Button></Box><Box sx={{ display: hook.isVisible_btnEstimate ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnEstimate_OnClick} sx={{ width: '144px', height: '24px', whiteSpace: "nowrap" }}>기준일자별 계산서발행</Button></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_btnPosReport ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnPosReport_OnClick} sx={{ width: '105px', height: '24px', whiteSpace: "nowrap" }}>통합영수증조회</Button></Box><Box sx={{ display: hook.isVisible_btnShowVirtualAccount ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnShowVirtualAccount_OnClick} sx={{ width: '92px', height: '24px', whiteSpace: "nowrap" }}>가상계좌보기</Button></Box><Box sx={{ display: hook.isVisible_btnChangeProcDate ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnChangeProcDate_OnClick} sx={{ width: '92px', height: '24px', whiteSpace: "nowrap" }}>처리일자변경</Button></Box><Box sx={{ display: hook.isVisible_btnProcRct ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnProcRct_OnClick} sx={{ width: '131px', height: '24px', whiteSpace: "nowrap" }}>현금영수증처리/취소</Button></Box><Box sx={{ display: hook.isVisible_btnPrintReRct ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnPrintReRct_OnClick} sx={{ width: '92px', height: '24px', whiteSpace: "nowrap" }}>영수증재발행</Button></Box><Box sx={{ display: hook.isVisible_btnPosvath ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnPrintEstimate_OnClick} sx={{ width: '79px', height: '24px', whiteSpace: "nowrap" }}>부가세정보</Button></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Stack direction="row" alignItems="center" spacing={0.5} sx={{ width: '187px', height: '22px', display: 'flex', alignItems: 'center', ml: '1128px' }}>
                    <Typography variant="body2" sx={{ minWidth: 88, bgcolor: '#f5f5f5', p: 0.3, borderRadius: 1 }}>E-Mail</Typography>
                    <TextField size="small" fullWidth  sx={{ "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" } }} />
                 </Stack><Stack direction="row" alignItems="center" spacing={0.5} sx={{ width: '118px', height: '22px', display: 'flex', alignItems: 'center', ml: '0px' }}>
                    <Typography variant="body2" sx={{ minWidth: 16, bgcolor: '#f5f5f5', p: 0.3, borderRadius: 1 }}>@</Typography>
                    <TextField size="small" fullWidth  sx={{ "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" } }} />
                 </Stack><Box sx={{ display: hook.isVisible_cbxEmailDomain ? undefined : 'none' }}><FormControl size="small" fullWidth sx={{ width: '92px', height: '22px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiSelect-select": { padding: "4px 6px !important" }, bgcolor: "#fff" }}><Select  displayEmpty><MenuItem value=""><em>선택</em></MenuItem>{ (Frmtraining0400MExamJubsuManagementData.ds_ds_oEmailDomain || []).map(opt => <MenuItem key={opt.CD} value={opt.CD}>{opt.DATA}</MenuItem>) }</Select></FormControl></Box><Box sx={{ display: hook.isVisible_btnSendEmail ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnSendEmail_OnClick} sx={{ width: '66px', height: '24px', whiteSpace: "nowrap" }}>메일발송</Button></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_gdSetlmentHist ? undefined : 'none' }}><Paper sx={{ width: '559px', height: '139px', width: '100%', height: 'auto', minHeight: '139px' }}><DataGridWrapper rows={hook.ds_oSetlmentHist} columns={columns_gdSetlmentHist} /></Paper></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_lbJubsuHist ? undefined : 'none' }}><Box sx={{ display: "flex", alignItems: "center", width: '120px', height: '22px' }}><Typography variant="body2">개인접수회차이력</Typography></Box></Box><Stack direction="row" alignItems="center" spacing={0.5} sx={{ width: '117px', height: '22px', display: 'flex', alignItems: 'center', ml: '18px' }}>
                    <Typography variant="body2" sx={{ minWidth: 55, bgcolor: '#f5f5f5', p: 0.3, borderRadius: 1 }}>EJMGNO</Typography>
                    <TextField size="small" fullWidth value={hook.ds_ioExamJubsu?.EJMGNO || ''} sx={{ "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" } }} />
                 </Stack><Stack direction="row" alignItems="center" spacing={0.5} sx={{ width: '121px', height: '22px', display: 'flex', alignItems: 'center', ml: '3px' }}>
                    <Typography variant="body2" sx={{ minWidth: 60, bgcolor: '#f5f5f5', p: 0.3, borderRadius: 1 }}>TPMGNO</Typography>
                    <TextField size="small" fullWidth value={hook.ds_ioExamJubsu?.TPMGNO || ''} sx={{ "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" } }} />
                 </Stack></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_gdJubsuInfo ? undefined : 'none' }}><Paper sx={{ width: '492px', height: '150px', width: '100%', height: 'auto', minHeight: '150px' }}><DataGridWrapper rows={hook.ds_oJubsuAllInfo} columns={columns_gdJubsuInfo} /></Paper></Box><Box sx={{ display: hook.isVisible_gdOrderHist ? undefined : 'none' }}><Paper sx={{ width: '496px', height: '150px', width: '100%', height: 'auto', minHeight: '150px' }}><DataGridWrapper rows={hook.ds_oOrderHist} columns={columns_gdOrderHist} /></Paper></Box></Stack>

                    </Paper>
                </Grid>
</Grid>

        </PageContainer>
    );
};
export default Frmtraining0400MExamJubsuManagement;

function CustomTabPanel(props) {
  const { children, value, index, ...other } = props;

  return (
    <div
      role="tabpanel"
      hidden={value !== index}
      id={`simple-tabpanel-${index}`}
      aria-labelledby={`simple-tab-${index}`}
      {...other}
    >
      {value === index && (
        <Box sx={{ p: 3 }}>
          {children}
        </Box>
      )}
    </div>
  );
}