// @ts-nocheck
import React, { useState } from 'react';
import { Box, Button, Dialog, DialogActions, DialogContent, DialogTitle, FormControl, FormControlLabel, Grid, IconButton, MenuItem, Paper, Radio, RadioGroup, Select, Stack, Tab, Tabs, TextField, Tooltip, Typography } from '@mui/material';
import { DatePicker } from '@mui/x-date-pickers/DatePicker';
import { Add, Check, Close, ContentCopy, Delete, Description, FilterList, Help, Print, Refresh, Save, Search, Sort, TouchApp, Visibility, ZoomIn } from '@mui/icons-material';
import DataGridWrapper from '../../components/DataGridWrapper';
import PageContainer from '../../components/PageContainer';
import { useFrmtraining0020MTrainingJubsuManagement } from './useFrmtraining0020MTrainingJubsuManagement';
import * as Frmtraining0020MTrainingJubsuManagementData from './Frmtraining0020MTrainingJubsuManagementData';
import { FrmCOM0100SWorkFormTitle } from '../COM/FrmCOM0100SWorkFormTitle';

export const Frmtraining0020MTrainingJubsuManagement = () => {
    const hook = useFrmtraining0020MTrainingJubsuManagement();
    const columns_gdSetlmentHist = [
        { field: 'TSSEQ', headerName: '순번', width: 30 },
        { field: 'TSPROCDATE', headerName: '처리일자', width: 71 },
        { field: 'TSSETLMTYN', headerName: '결제여부', width: 62 },
        { field: 'EARLYSUNAPGUBUN', headerName: '선수납', width: 55 },
        { field: 'TSGUBUNCDNM', headerName: '결제구분', width: 70 },
        { field: 'TSGUBUNNM', headerName: '결제방법', width: 106 },
        { field: 'TSPROCAMOUNT', headerName: '금액(원)', width: 62 },
        { field: 'PVINFO', headerName: '계산서', width: 55 },
        { field: 'TAXRCPTYN', headerName: '세금계산서발행여부', width: 0 },
        { field: 'TSPROCGTMGNONM', headerName: '처리지부', width: 70 },
        { field: 'PROCSABUN', headerName: '처리자', width: 73 },
        { field: 'TSJUMUNNO', headerName: '주문번호', width: 94 },
        { field: 'TSREPAYREF', headerName: '환불No', width: 55 },
        { field: 'TSMGGTMGNONM', headerName: '관리지부', width: 70 },
        { field: 'TSPOSGTMGNONM', headerName: 'POS지부', width: 70 },
        { field: 'TSPONYDATE', headerName: '정산일자', width: 77 },
    ];
    const columns_gdJubsuInfo = [
        { field: 'id', headerName: '순번', width: 35, renderCell: (params) => params.api.getAllRowIds().indexOf(params.id) + 1 },
        { field: 'MGJIBUCD', headerName: '지부', width: 60 },
        { field: 'YEAR', headerName: '년도', width: 36 },
        { field: 'COURSEMUNJECD', headerName: '직능', width: 140 },
        { field: 'TORDER', headerName: '회차', width: 31 },
        { field: 'JUBSUNO', headerName: '접수번호', width: 58 },
        { field: 'PASSDATE', headerName: '수료일자', width: 83 },
        { field: 'LASTSUNAPGUBUN', headerName: '환불여부', width: 59 },
        { field: 'FIRSTREGDATE', headerName: '접수일자', width: 83 },
    ];
    const columns_gdOrderHist = [
        { field: 'id', headerName: '순번', width: 35, renderCell: (params) => params.api.getAllRowIds().indexOf(params.id) + 1 },
        { field: 'BEFORJIBU', headerName: '지부', width: 70 },
        { field: 'BEFORORDER', headerName: '회차', width: 50 },
        { field: 'BEFORJUBSUNO', headerName: '접수번호', width: 60 },
        { field: 'AFTERJIBU', headerName: '변경 후', width: 70 },
        { field: 'AFTERORDER', headerName: '회차', width: 50 },
        { field: 'AFTERJUBSUNO', headerName: '접수번호', width: 60 },
        { field: 'PROCDATE', headerName: '처리일자', width: 85 },
        { field: 'REMARK', headerName: '사유', width: 189 },
        { field: 'LASTSUNAPGUBUN', headerName: '환불여부', width: 60 },
        { field: 'ABSENTYN', headerName: '결강일차', width: 70 },
    ];
    return (
        <PageContainer>

            <Stack direction="row" alignItems="center" justifyContent="space-between" mb={2}>
                <Typography variant="h5">기본정보</Typography>
                <Stack direction="row" spacing={1}>
                    <Button variant="contained" startIcon={<Search />} onClick={hook.lfn_Search}>조회</Button>
<Button variant="contained" startIcon={<Save />} onClick={hook.lfn_Delete}>삭제 저장</Button>
<Button variant="contained" startIcon={<Save />} onClick={hook.lfn_Save}>수정 저장</Button>
<Button variant="contained" startIcon={<Add />} onClick={hook.lfn_Cancel}>입력 초기화</Button>
<Button variant="contained" startIcon={<Print />} onClick={hook.lfn_PrintScreen}>화면 출력</Button>
<Button variant="contained" startIcon={<Close />} onClick={hook.lfn_End}>닫기</Button>
<Button variant="contained" startIcon={<Print />} onClick={hook.btnPrintJubsu_OnClick}>수강증출력</Button>
<Button variant="contained" startIcon={<Print />} onClick={hook.lfn_Print}>강습원서출력(F9)</Button>
<Button variant="contained" startIcon={<Print />} onClick={hook.btnPrintJubsuResult_OnClick}>접수결과출력</Button>

                </Stack>
            </Stack>
<Grid container spacing={2}>

                <Grid item xs={12} md={8}>
                    <Paper sx={{ p: 2, height: '100%' }}>
                        <Typography variant="subtitle2" sx={{ mb: 2, fontWeight: 'bold' }}>Detailed Info</Typography>
                        <Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "58px", py: 0.5, width: "100%" }}><Stack direction="row" alignItems="center" spacing={0.5} sx={{ width: '179px', height: '22px', display: 'flex', alignItems: 'center', ml: '8px' }}>
                    <Typography variant="body2" sx={{ minWidth: 88, bgcolor: '#f5f5f5', p: 0.3, borderRadius: 1 }}>지부</Typography>
                    <FormControl size="small" fullWidth sx={{ "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiSelect-select": { padding: "4px 6px !important" } }}><Select  displayEmpty><MenuItem value=""><em>선택</em></MenuItem>{ (Frmtraining0020MTrainingJubsuManagementData.ds_ds_oJibu || []).map(opt => <MenuItem key={opt.CD} value={opt.CD}>{opt.DATA}</MenuItem>) }</Select></FormControl>
                 </Stack><Stack direction="row" alignItems="center" spacing={0.5} sx={{ width: '128px', height: '22px', display: 'flex', alignItems: 'center', ml: '5px' }}>
                    <Typography variant="body2" sx={{ minWidth: 88, bgcolor: '#f5f5f5', p: 0.3, borderRadius: 1 }}>년도</Typography>
                    <TextField size="small" fullWidth  sx={{ "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" } }} />
                 </Stack><Box sx={{ display: hook.isVisible_lbPersonNm ? undefined : 'none' }}><Box sx={{ display: "flex", alignItems: "center", width: '88px', height: '22px' }}><Typography variant="body2">성명</Typography></Box></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "4px", py: 0.5, width: "100%" }}><Stack direction="row" alignItems="center" spacing={0.5} sx={{ width: '335px', height: '125px', display: 'flex', alignItems: 'center', ml: '8px' }}>
                    <Typography variant="body2" sx={{ minWidth: 16, bgcolor: '#f5f5f5', p: 0.3, borderRadius: 1 }}>직능</Typography>
                    <FormControl component="fieldset" sx={{ width: "max-content", whiteSpace: "nowrap" }}><RadioGroup row sx={{ flexWrap: "nowrap" }} >{ (Frmtraining0020MTrainingJubsuManagementData.ds_ds_oCourse || []).map(opt => <FormControlLabel key={opt.CD} value={opt.CD} control={<Radio />} label={opt.DATA} sx={{ whiteSpace: 'nowrap', flexShrink: 0, mr: 2 }} />) }</RadioGroup></FormControl>
                 </Stack><Box sx={{ display: hook.isVisible_lbResidentNo ? undefined : 'none' }}><Box sx={{ display: "flex", alignItems: "center", width: '88px', height: '22px' }}><Typography variant="body2">주민번호</Typography></Box></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_lbHpTel ? undefined : 'none' }}><Box sx={{ display: "flex", alignItems: "center", width: '88px', height: '22px' }}><Typography variant="body2">휴대폰</Typography></Box></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "4px", py: 0.5, width: "100%" }}><Stack direction="row" alignItems="center" spacing={0.5} sx={{ width: '87px', height: '22px', display: 'flex', alignItems: 'center', ml: '352px' }}>
                    <Typography variant="body2" sx={{ minWidth: 32, bgcolor: '#f5f5f5', p: 0.3, borderRadius: 1 }}>주소</Typography>
                    <TextField size="small" fullWidth value={hook.ds_ioTrainingJubsu?.ZIPCD || ''} sx={{ "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" } }} />
                 </Stack><Box sx={{ display: hook.isVisible_btnSearchZipCode ? undefined : 'none' }}><Button variant="outlined"  onClick={hook.btnSearchZipCode_OnClick} size="small" sx={{ minWidth: 26, p: 0.2, width: '22px', height: '24px', whiteSpace: "nowrap" }}><Search fontSize="small" /></Button></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "26px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_lbTel ? undefined : 'none' }}><Box sx={{ display: "flex", alignItems: "center", width: '88px', height: '22px' }}><Typography variant="body2">전화번호</Typography></Box></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "4px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_lbEmail ? undefined : 'none' }}><Box sx={{ display: "flex", alignItems: "center", width: '88px', height: '22px' }}><Typography variant="body2">E-Mail</Typography></Box></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Stack direction="row" alignItems="center" spacing={0.5} sx={{ width: '120px', height: '22px', display: 'flex', alignItems: 'center', ml: '8px' }}>
                    <Typography variant="body2" sx={{ minWidth: 88, bgcolor: '#f5f5f5', p: 0.3, borderRadius: 1 }}>회차</Typography>
                    <TextField size="small" fullWidth  sx={{ "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" } }} />
                 </Stack><Box sx={{ display: hook.isVisible_btnSearchTrainingOrder ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnSearchTrainingOrder_OnClick} sx={{ width: '92px', height: '24px', whiteSpace: "nowrap" }}>접수가능회차</Button></Box><Box sx={{ display: hook.isVisible_btnAwaiter ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnAwaiter_OnClick} sx={{ width: '106px', height: '24px', whiteSpace: "nowrap" }}>ⓘ접수대기자보기</Button></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_Static1 ? undefined : 'none' }}><Box sx={{ display: "flex", alignItems: "center", width: '88px', height: '22px' }}><Typography variant="body2">선·후불구분</Typography></Box></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Stack direction="row" alignItems="center" spacing={0.5} sx={{ width: '142px', height: '22px', display: 'flex', alignItems: 'center', ml: '8px' }}>
                    <Typography variant="body2" sx={{ minWidth: 88, bgcolor: '#f5f5f5', p: 0.3, borderRadius: 1 }}>접수번호</Typography>
                    <TextField size="small" fullWidth  sx={{ "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" } }} />
                 </Stack><Box sx={{ display: hook.isVisible_btnSeqList ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnSeqList_OnClick} sx={{ width: '92px', height: '24px', whiteSpace: "nowrap" }}>접수목록</Button></Box><Box sx={{ display: hook.isVisible_btnUnUseJubsuNo ? undefined : 'none' }}><Button variant="contained"   onClick={hook.lfn_SearchUnUseJubsuNo} sx={{ width: '66px', height: '24px', whiteSpace: "nowrap" }}>빈번호</Button></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_lbRemark ? undefined : 'none' }}><Box sx={{ display: "flex", alignItems: "center", width: '88px', height: '22px' }}><Typography variant="body2">비고(특이사항)</Typography></Box></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Stack direction="row" alignItems="center" spacing={0.5} sx={{ width: '142px', height: '22px', display: 'flex', alignItems: 'center', ml: '8px' }}>
                    <Typography variant="body2" sx={{ minWidth: 88, bgcolor: '#f5f5f5', p: 0.3, borderRadius: 1 }}>좌석번호</Typography>
                    <TextField size="small" fullWidth  sx={{ "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" } }} />
                 </Stack><Box sx={{ display: hook.isVisible_btnSeatList ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnSeatList_OnClick} sx={{ width: '92px', height: '24px', whiteSpace: "nowrap" }}>좌석목록</Button></Box><Box sx={{ display: hook.isVisible_btnUnSeatList ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnUnSeatList_OnClick} sx={{ width: '66px', height: '24px', whiteSpace: "nowrap" }}>좌석선택</Button></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_Static6 ? undefined : 'none' }}><Box sx={{ display: "flex", alignItems: "center", width: '88px', height: '70px' }}><Typography variant="body2">실시간 온라인</Typography></Box></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_lbTrainingInfo ? undefined : 'none' }}><Box sx={{ display: "flex", alignItems: "center", width: '36px', height: '69px' }}><Typography variant="body2">회차정보</Typography></Box></Box><Box sx={{ display: hook.isVisible_lbTrainingInfo1 ? undefined : 'none' }}><Box sx={{ display: "flex", alignItems: "center", width: '294px', height: '24px' }}><Typography variant="body2"></Typography></Box></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_lbTrainingInfo2 ? undefined : 'none' }}><Box sx={{ display: "flex", alignItems: "center", width: '294px', height: '24px' }}><Typography variant="body2"></Typography></Box></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_lbTrainingInfo3 ? undefined : 'none' }}><Box sx={{ display: "flex", alignItems: "center", width: '294px', height: '24px' }}><Typography variant="body2"></Typography></Box></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_lbOrderChange ? undefined : 'none' }}><Box sx={{ display: "flex", alignItems: "center", width: '88px', height: '22px' }}><Typography variant="body2">회차변경</Typography></Box></Box><Box sx={{ display: hook.isVisible_btnTrainingJubsuModify ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnTrainingJubsuModify_OnClick} sx={{ width: '85px', height: '24px', whiteSpace: "nowrap" }}>회차변경</Button></Box><Box sx={{ display: hook.isVisible_Static3 ? undefined : 'none' }}><Box sx={{ display: "flex", alignItems: "center", width: '88px', height: '22px' }}><Typography variant="body2">민원서류 등록</Typography></Box></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "3px", py: 0.5, width: "100%" }}><Stack direction="row" alignItems="center" spacing={0.5} sx={{ width: '160px', height: '22px', display: 'flex', alignItems: 'center', ml: '8px' }}>
                    <Typography variant="body2" sx={{ minWidth: 112, bgcolor: '#f5f5f5', p: 0.3, borderRadius: 1 }}>실무능력평가 결과</Typography>
                    <TextField size="small" fullWidth value={hook.ds_ioTrainingJubsu?.EVALYN || ''} sx={{ "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" } }} />
                 </Stack></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_lbSetlmt ? undefined : 'none' }}><Box sx={{ display: "flex", alignItems: "center", width: '100px', height: '22px' }}><Typography variant="body2">결제내역</Typography></Box></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Stack direction="row" alignItems="center" spacing={0.5} sx={{ width: '128px', height: '22px', display: 'flex', alignItems: 'center', ml: '8px' }}>
                    <Typography variant="body2" sx={{ minWidth: 88, bgcolor: '#f5f5f5', p: 0.3, borderRadius: 1 }}>수료여부</Typography>
                    <TextField size="small" fullWidth value={hook.ds_ioTrainingJubsu?.PASSYN || ''} sx={{ "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" } }} />
                 </Stack><Box sx={{ display: hook.isVisible_btnPosReport ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnPosReport_OnClick} sx={{ width: '92px', height: '24px', whiteSpace: "nowrap" }}>통합영수증조회</Button></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Stack direction="row" alignItems="center" spacing={0.5} sx={{ width: '224px', height: '22px', display: 'flex', alignItems: 'center', ml: '8px' }}>
                    <Typography variant="body2" sx={{ minWidth: 88, bgcolor: '#f5f5f5', p: 0.3, borderRadius: 1 }}>결강여부</Typography>
                    <TextField size="small" fullWidth value={hook.ds_ioTrainingJubsu?.ABSENTYN || ''} sx={{ "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" } }} />
                 </Stack><Box sx={{ display: hook.isVisible_btnAbsentManageLink ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnAbsentManageLink_OnClick} sx={{ width: '79px', height: '24px', whiteSpace: "nowrap" }}>결강자관리</Button></Box><Box sx={{ display: hook.isVisible_btnSetlmt ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnSetlmt_OnClick} sx={{ width: '96px', height: '134px', whiteSpace: "nowrap" }}>결제(POS)</Button></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_Static9 ? undefined : 'none' }}><Box sx={{ display: "flex", alignItems: "center", width: '88px', height: '22px' }}><Typography variant="body2">사이버교육</Typography></Box></Box><Box sx={{ display: hook.isVisible_btnCyberInfo ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnCyberInfo_OnClick} sx={{ width: '118px', height: '24px', whiteSpace: "nowrap" }}>사이버교육 정보</Button></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "4px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_Static10 ? undefined : 'none' }}><Box sx={{ display: "flex", alignItems: "center", width: '88px', height: '22px' }}><Typography variant="body2">수첩정보</Typography></Box></Box><Box sx={{ display: hook.isVisible_btnLicenseList ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnLicenseList_OnClick} sx={{ width: '92px', height: '24px', whiteSpace: "nowrap" }}>수첩보유현황</Button></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "3px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_Static11 ? undefined : 'none' }}><Box sx={{ display: "flex", alignItems: "center", width: '88px', height: '22px' }}><Typography variant="body2">이력정보</Typography></Box></Box><Box sx={{ display: hook.isVisible_btnJubsuHistory ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnJubsuHistory_OnClick} sx={{ width: '66px', height: '24px', whiteSpace: "nowrap" }}>접수이력</Button></Box><Box sx={{ display: hook.isVisible_btnModifyHistory ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnModifyHistory_OnClick} sx={{ width: '66px', height: '24px', whiteSpace: "nowrap" }}>변경이력</Button></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "23px", py: 0.5, width: "100%" }}><Stack direction="row" alignItems="center" spacing={0.5} sx={{ width: '188px', height: '22px', display: 'flex', alignItems: 'center', ml: '8px' }}>
                    <Typography variant="body2" sx={{ minWidth: 88, bgcolor: '#f5f5f5', p: 0.3, borderRadius: 1 }}>수강증 바코드</Typography>
                    <TextField size="small" fullWidth  sx={{ "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" } }} />
                 </Stack><Box sx={{ display: hook.isVisible_btnBarCodeSearch ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnBarCodeSearch_OnClick} sx={{ width: '125px', height: '24px', whiteSpace: "nowrap" }}>바코드로 조회</Button></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "18px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_lbJubsuInfo ? undefined : 'none' }}><Box sx={{ display: "flex", alignItems: "center", width: '120px', height: '22px' }}><Typography variant="body2">개인접수정보</Typography></Box></Box></Stack>

                    </Paper>
                </Grid>

                <Grid item xs={12} md={4}>
                    <Paper sx={{ p: 2, height: '100%' }}>
                        <Typography variant="subtitle2" sx={{ mb: 2, fontWeight: 'bold' }}>List</Typography>
                        <Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "45px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_imgLastestPicture ? undefined : 'none' }}><Box sx={{ width: '92px', height: '107px', border: "1px solid #ddd", display: "flex", alignItems: "center", justifyContent: "center" }}>Image: imgLastestPicture</Box></Box><Box sx={{ display: hook.isVisible_imgPicture ? undefined : 'none' }}><Box sx={{ width: '112px', height: '146px', border: "1px solid #ddd", display: "flex", alignItems: "center", justifyContent: "center" }}>Image: imgPicture</Box></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_edPersonNm ? undefined : 'none' }}><TextField size="small" fullWidth value={hook.ds_ioTrainingJubsu?.PERSONNM || ''} sx={{ width: '106px', height: '22px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" }, bgcolor: "#fff" }} /></Box><Box sx={{ display: hook.isVisible_btnSearchPersonInfo ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnSearchPersonInfo_OnClick} sx={{ width: '118px', height: '24px', whiteSpace: "nowrap" }}>접수자 검색</Button></Box><Box sx={{ display: hook.isVisible_Button0 ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnSearchPersonInfoChange_OnClick} sx={{ width: '105px', height: '24px', whiteSpace: "nowrap" }}>접수자정보변경</Button></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_medResidentNo ? undefined : 'none' }}><TextField size="small" fullWidth value={hook.ds_ioTrainingJubsu?.BIRTHDAY7 || ''} sx={{ width: '106px', height: '22px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" }, bgcolor: "#fff" }} /></Box><Box sx={{ display: hook.isVisible_btnTraingJubsuHist ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnTraingJubsuHist_OnClick} sx={{ width: '118px', height: '24px', whiteSpace: "nowrap" }}>기존접수이력(F6)</Button></Box><Box sx={{ display: hook.isVisible_btnAuthResidentNo ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnAuthResidentNo_OnClick} sx={{ width: '105px', height: '24px', whiteSpace: "nowrap" }}>실명인증</Button></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_edHpTel ? undefined : 'none' }}><TextField size="small" fullWidth value={hook.ds_ioTrainingJubsu?.HPTEL || ''} sx={{ width: '104px', height: '22px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" }, bgcolor: "#fff" }} /></Box><Box sx={{ display: hook.isVisible_btnSendSms ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnSendSms_OnClick} sx={{ width: '118px', height: '24px', whiteSpace: "nowrap" }}>문자발송</Button></Box><Box sx={{ display: hook.isVisible_btnSmsStat ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnSmsStat_OnClick} sx={{ width: '105px', height: '24px', whiteSpace: "nowrap" }}>문자현황</Button></Box><Box sx={{ display: hook.isVisible_btnPictureManagement ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnPictureManagement_OnClick} sx={{ width: '93px', height: '24px', whiteSpace: "nowrap" }}>사진관리</Button></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_edAddr1 ? undefined : 'none' }}><TextField size="small" fullWidth value={hook.ds_ioTrainingJubsu?.ADDR1 || ''} sx={{ width: '329px', height: '22px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" }, bgcolor: "#fff" }} /></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "3px", py: 0.5, width: "100%" }}><Box sx={{ ml: "352px", minWidth: "444px" }}><Box sx={{ display: hook.isVisible_edAddr2 ? undefined : 'none' }}><TextField size="small" fullWidth value={hook.ds_ioTrainingJubsu?.ADDR2 || ''} sx={{ width: '442px', height: '22px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" }, bgcolor: "#fff" }} /></Box><Box sx={{ display: hook.isVisible_cbxAddrGubun ? undefined : 'none' }}><FormControl size="small" fullWidth sx={{ width: '89px', height: '22px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiSelect-select": { padding: "4px 6px !important" }, bgcolor: "#fff" }}><Select value={hook.ds_ioTrainingJubsu?.TJADDRGUBUN || ''} displayEmpty><MenuItem value=""><em>선택</em></MenuItem>{ (Frmtraining0020MTrainingJubsuManagementData.ds_ds_oAddr || []).map(opt => <MenuItem key={opt.CD} value={opt.CD}>{opt.DATA}</MenuItem>) }</Select></FormControl></Box></Box><Box sx={{ display: hook.isVisible_btnApplyPicture ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnApplyPicture_OnClick} sx={{ width: '93px', height: '24px', whiteSpace: "nowrap" }}>최근사진반영</Button></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_edTel ? undefined : 'none' }}><TextField size="small" fullWidth value={hook.ds_ioTrainingJubsu?.TEL || ''} sx={{ width: '104px', height: '22px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" }, bgcolor: "#fff" }} /></Box><Box sx={{ display: hook.isVisible_edCARGUBUN ? undefined : 'none' }}><TextField size="small" fullWidth  sx={{ width: '38px', height: '22px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" }, bgcolor: "#fff" }} /></Box><Box sx={{ display: hook.isVisible_edMANAGE_VRSC_AT ? undefined : 'none' }}><TextField size="small" fullWidth  sx={{ width: '30px', height: '22px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" }, bgcolor: "#fff" }} /></Box><Box sx={{ display: hook.isVisible_edLTCCOURECD ? undefined : 'none' }}><TextField size="small" fullWidth  sx={{ width: '30px', height: '22px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" }, bgcolor: "#fff" }} /></Box><Box sx={{ display: hook.isVisible_btnEmailStat ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnEmailStat_OnClick} sx={{ width: '66px', height: '24px', whiteSpace: "nowrap" }}>메일현황</Button></Box><Box sx={{ display: hook.isVisible_btnSearchRegPicture ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnSearchRegPicture_OnClick} sx={{ width: '93px', height: '24px', whiteSpace: "nowrap" }}>등록사진조회</Button></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_edEmail ? undefined : 'none' }}><TextField size="small" fullWidth value={hook.ds_ioTrainingJubsu?.EMAILID || ''} sx={{ width: '95px', height: '22px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" }, bgcolor: "#fff" }} /></Box><Stack direction="row" alignItems="center" spacing={0.5} sx={{ width: '118px', height: '22px', display: 'flex', alignItems: 'center', ml: '0px' }}>
                    <Typography variant="body2" sx={{ minWidth: 16, bgcolor: '#f5f5f5', p: 0.3, borderRadius: 1 }}>@</Typography>
                    <TextField size="small" fullWidth value={hook.ds_ioTrainingJubsu?.EMAILDOMAIN || ''} sx={{ "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" } }} />
                 </Stack><Box sx={{ display: hook.isVisible_cbxEmailDomain ? undefined : 'none' }}><FormControl size="small" fullWidth sx={{ width: '92px', height: '22px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiSelect-select": { padding: "4px 6px !important" }, bgcolor: "#fff" }}><Select  displayEmpty><MenuItem value=""><em>선택</em></MenuItem>{ (Frmtraining0020MTrainingJubsuManagementData.ds_ds_oEmailDomain || []).map(opt => <MenuItem key={opt.CD} value={opt.CD}>{opt.DATA}</MenuItem>) }</Select></FormControl></Box><Box sx={{ ml: "2px", minWidth: "157px" }}><Box sx={{ display: hook.isVisible_btnSendEmail ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnSendEmail_OnClick} sx={{ width: '66px', height: '24px', whiteSpace: "nowrap" }}>메일발송</Button></Box><Box sx={{ display: hook.isVisible_btnScanPicture ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnScanPicture_OnClick} sx={{ width: '105px', height: '24px', whiteSpace: "nowrap" }}>SVP5300사진스캔</Button></Box></Box><Box sx={{ display: hook.isVisible_btnPhotoScan ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnPhotoScan_OnClick} sx={{ width: '97px', height: '26px', whiteSpace: "nowrap" }}>D400사진스캔</Button></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_divTask ? undefined : 'none' }}><Paper sx={{ p: 2, width: '207px', height: '98px', width: '100%', height: 'auto', minHeight: '98px', overflow: 'auto' }}><Typography variant="subtitle2" sx={{ mb: 1, fontWeight: "bold" }}>Div0</Typography><Stack direction="column" spacing={0}></Stack></Paper></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_radAmountGubun ? undefined : 'none' }}><FormControl component="fieldset" sx={{ width: '140px', height: '24px', width: "max-content", whiteSpace: "nowrap", pr: 2 }}><RadioGroup row sx={{ flexWrap: "nowrap" }} value={hook.ds_ioTrainingJubsu?.TJAMOUNTGUBUN || ''}>{ (Frmtraining0020MTrainingJubsuManagementData.ds_ds_oAmountGubun || []).map(opt => <FormControlLabel key={opt.CD} value={opt.CD} control={<Radio />} label={opt.DATA} sx={{ whiteSpace: 'nowrap', flexShrink: 0, mr: 2 }} />) }</RadioGroup></FormControl></Box><Stack direction="row" alignItems="center" spacing={0.5} sx={{ width: '302px', height: '22px', display: 'flex', alignItems: 'center', ml: '2px' }}>
                    <Typography variant="body2" sx={{ minWidth: 88, bgcolor: '#f5f5f5', p: 0.3, borderRadius: 1 }}>근무처</Typography>
                    <TextField size="small" fullWidth value={hook.ds_ioTrainingJubsu?.COMPNM || ''} sx={{ "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" } }} />
                 </Stack><Box sx={{ display: hook.isVisible_btnLoadScanPicture ? undefined : 'none' }}><Button variant="contained" color="success"  onClick={hook.btnLoadScanPicture_OnClick} sx={{ width: '119px', height: '24px', whiteSpace: "nowrap" }}>스캔사진불러오기</Button></Box><Stack direction="row" alignItems="center" spacing={0.5} sx={{ width: '228px', height: '24px', display: 'flex', alignItems: 'center', ml: '23px' }}>
                    <Typography variant="body2" sx={{ minWidth: 116, bgcolor: '#f5f5f5', p: 0.3, borderRadius: 1 }}>안전원회원가입동의</Typography>
                    <FormControl component="fieldset" sx={{ width: "max-content", whiteSpace: "nowrap" }}><RadioGroup row sx={{ flexWrap: "nowrap" }} value={hook.ds_ioTrainingJubsu?.TJMEMAGREEGUBUN || ''}>{ (Frmtraining0020MTrainingJubsuManagementData.ds_ds_oYN || []).map(opt => <FormControlLabel key={opt.CD} value={opt.CD} control={<Radio />} label={opt.DATA} sx={{ whiteSpace: 'nowrap', flexShrink: 0, mr: 2 }} />) }</RadioGroup></FormControl>
                 </Stack></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_cbxRemarkGubun ? undefined : 'none' }}><FormControl size="small" fullWidth sx={{ width: '88px', height: '22px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiSelect-select": { padding: "4px 6px !important" }, bgcolor: "#fff" }}><Select value={hook.ds_ioTrainingJubsu?.REMARKCD || ''} displayEmpty><MenuItem value=""><em>선택</em></MenuItem>{ (Frmtraining0020MTrainingJubsuManagementData.ds_ds_oRemarkGubun || []).map(opt => <MenuItem key={opt.CD} value={opt.CD}>{opt.DATA}</MenuItem>) }</Select></FormControl></Box><Box sx={{ display: hook.isVisible_edRemark ? undefined : 'none' }}><TextField size="small" fullWidth value={hook.ds_ioTrainingJubsu?.REMARK || ''} sx={{ width: '356px', height: '22px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" }, bgcolor: "#fff" }} /></Box><Box sx={{ display: hook.isVisible_btnLoadPicture ? undefined : 'none' }}><Button variant="contained" color="success"  onClick={hook.btnLoadPicture_OnClick} sx={{ width: '119px', height: '24px', whiteSpace: "nowrap" }}>사진찾기</Button></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_fdAttachFile ? undefined : 'none' }}><Button variant="contained" color="success" startIcon={<Description />} sx={{ width: '24px', height: '26px', whiteSpace: "nowrap" }}>fdAttachFile</Button></Box><Box sx={{ display: hook.isVisible_hfAttachFile ? undefined : 'none' }}><Button variant="contained" color="success" startIcon={<Description />} sx={{ width: '24px', height: '26px', whiteSpace: "nowrap" }}>hfAttachFile</Button></Box><Box sx={{ display: hook.isVisible_fiAttachFile ? undefined : 'none' }}><Button variant="contained" color="success" startIcon={<Description />} sx={{ width: '24px', height: '26px', whiteSpace: "nowrap" }}>fiAttachFile</Button></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Stack direction="row" alignItems="center" spacing={0.5} sx={{ width: '187px', height: '22px', display: 'flex', alignItems: 'center', ml: '445px' }}>
                    <Typography variant="body2" sx={{ minWidth: 88, bgcolor: '#f5f5f5', p: 0.3, borderRadius: 1 }}>온라인 여부</Typography>
                    <TextField size="small" fullWidth value={hook.ds_ioTrainingJubsu?.TOONLINEGUBUNNM || ''} sx={{ "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" } }} />
                 </Stack><Stack direction="row" alignItems="center" spacing={0.5} sx={{ width: '250px', height: '22px', display: 'flex', alignItems: 'center', ml: '6px' }}>
                    <Typography variant="body2" sx={{ minWidth: 170, bgcolor: '#f5f5f5', p: 0.3, borderRadius: 1 }}>실무능력평가 과제제출 여부</Typography>
                    <TextField size="small" fullWidth value={hook.ds_ioTrainingJubsu?.TJTASKSUBMITGUBUNNM || ''} sx={{ "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" } }} />
                 </Stack><Box sx={{ display: hook.isVisible_btnDownload ? undefined : 'none' }}><Button variant="contained" color="success"  onClick={hook.btnDownload_OnClick} sx={{ width: '53px', height: '24px', whiteSpace: "nowrap" }}>다운로드</Button></Box><Box sx={{ display: hook.isVisible_btnTaskSave ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnTaskSave_OnClick} sx={{ width: '53px', height: '24px', whiteSpace: "nowrap" }}>과제등록</Button></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "3px", py: 0.5, width: "100%" }}><Stack direction="row" alignItems="center" spacing={0.5} sx={{ width: '144px', height: '22px', display: 'flex', alignItems: 'center', ml: '444px' }}>
                    <Typography variant="body2" sx={{ minWidth: 88, bgcolor: '#f5f5f5', p: 0.3, borderRadius: 1 }}>교재수령지</Typography>
                    <TextField size="small" fullWidth value={hook.ds_ioTrainingJubsu?.TPBOOKZIPCD || ''} sx={{ "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" } }} />
                 </Stack><Box sx={{ display: hook.isVisible_btnSearchZipCode2 ? undefined : 'none' }}><Button variant="outlined"  onClick={hook.btnSearchZipCode2_OnClick} size="small" sx={{ minWidth: 26, p: 0.2, width: '22px', height: '24px', whiteSpace: "nowrap" }}><Search fontSize="small" /></Button></Box><Box sx={{ display: hook.isVisible_edBookAddr1 ? undefined : 'none' }}><TextField size="small" fullWidth value={hook.ds_ioTrainingJubsu?.TPBOOKADDR1 || ''} sx={{ width: '392px', height: '22px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" }, bgcolor: "#fff" }} /></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_edBookAddr2 ? undefined : 'none' }}><TextField size="small" fullWidth value={hook.ds_ioTrainingJubsu?.TPBOOKADDR2 || ''} sx={{ width: '267px', height: '22px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" }, bgcolor: "#fff" }} /></Box><Box sx={{ display: hook.isVisible_edBookPrint ? undefined : 'none' }}><TextField size="small" fullWidth  sx={{ width: '90px', height: '23px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" }, bgcolor: "#fff" }} /></Box><Box sx={{ display: hook.isVisible_edBookPrintYn ? undefined : 'none' }}><TextField size="small" fullWidth value={hook.ds_ioTrainingJubsu?.TJBOOKPRINTTOMGNO || ''} sx={{ width: '30px', height: '22px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" }, bgcolor: "#fff" }} /></Box><Stack direction="row" alignItems="center" spacing={0.5} sx={{ width: '169px', height: '24px', display: 'flex', alignItems: 'center', ml: '1px' }}>
                    <Typography variant="body2" sx={{ minWidth: 55, bgcolor: '#f5f5f5', p: 0.3, borderRadius: 1 }}>교재반납</Typography>
                    <FormControl component="fieldset" sx={{ width: "max-content", whiteSpace: "nowrap" }}><RadioGroup row sx={{ flexWrap: "nowrap" }} value={hook.ds_ioTrainingJubsu?.TJBOOKRETURNYN || ''}>{ (Frmtraining0020MTrainingJubsuManagementData.ds_ds_oBookReturn || []).map(opt => <FormControlLabel key={opt.CD} value={opt.CD} control={<Radio />} label={opt.DATA} sx={{ whiteSpace: 'nowrap', flexShrink: 0, mr: 2 }} />) }</RadioGroup></FormControl>
                 </Stack></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "4px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_cbxForm ? undefined : 'none' }}><FormControl size="small" fullWidth sx={{ width: '172px', height: '22px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiSelect-select": { padding: "4px 6px !important" }, bgcolor: "#fff" }}><Select  displayEmpty><MenuItem value=""><em>선택</em></MenuItem>{ (Frmtraining0020MTrainingJubsuManagementData.ds_ds_oForm || []).map(opt => <MenuItem key={opt.CD} value={opt.CD}>{opt.DATA}</MenuItem>) }</Select></FormControl></Box><Box sx={{ display: hook.isVisible_edFormResult ? undefined : 'none' }}><TextField size="small" fullWidth  sx={{ width: '45px', height: '22px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" }, bgcolor: "#fff" }} /></Box><Box sx={{ display: hook.isVisible_btnSeverFormView ? undefined : 'none' }}><Button variant="outlined"  onClick={hook.btnSeverFormView_OnClick} size="small" sx={{ minWidth: 26, p: 0.2, width: '22px', height: '24px', whiteSpace: "nowrap" }}><Search fontSize="small" /></Button></Box><Box sx={{ display: hook.isVisible_btnScan ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnScan_OnClick} sx={{ width: '66px', height: '24px', whiteSpace: "nowrap" }}>①스캔실행</Button></Box><Box sx={{ display: hook.isVisible_btnScanSearch ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnScanSearch_OnClick} sx={{ width: '66px', height: '24px', whiteSpace: "nowrap" }}>②불러오기</Button></Box><Box sx={{ display: hook.isVisible_edScanFileName ? undefined : 'none' }}><TextField size="small" fullWidth  sx={{ width: '74px', height: '22px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" }, bgcolor: "#fff" }} /></Box><Box sx={{ display: hook.isVisible_btnLocalFormView ? undefined : 'none' }}><Button variant="outlined"  onClick={hook.btnLocalFormView_OnClick} size="small" sx={{ minWidth: 26, p: 0.2, width: '22px', height: '24px', whiteSpace: "nowrap" }}><Search fontSize="small" /></Button></Box><Box sx={{ display: hook.isVisible_btnScanSave ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnScanSave_OnClick} sx={{ width: '66px', height: '24px', whiteSpace: "nowrap" }}>③서류저장</Button></Box><Box sx={{ display: hook.isVisible_btnFormDelete ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnFormDelete_OnClick} sx={{ width: '16px', height: '22px', whiteSpace: "nowrap" }}>서류삭제</Button></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "6px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_fdImage2 ? undefined : 'none' }}><Button variant="contained" color="success" startIcon={<Description />} sx={{ width: '24px', height: '26px', whiteSpace: "nowrap" }}>fdImage2</Button></Box><Box sx={{ display: hook.isVisible_hfImage2 ? undefined : 'none' }}><Button variant="contained" color="success" startIcon={<Description />} sx={{ width: '24px', height: '26px', whiteSpace: "nowrap" }}>hfImage2</Button></Box><Box sx={{ display: hook.isVisible_fiImageFile2 ? undefined : 'none' }}><Button variant="contained" color="success" startIcon={<Description />} sx={{ width: '24px', height: '26px', whiteSpace: "nowrap" }}>fiImageFile2</Button></Box><Box sx={{ display: hook.isVisible_btnDeleteSettlement ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnDeleteSettlement_OnClick} sx={{ width: '81px', height: '24px', whiteSpace: "nowrap" }}>결제삭제</Button></Box><Box sx={{ display: hook.isVisible_btnPrintReRctPDF ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnPrintReRctPDF_OnClick} sx={{ width: '133px', height: '24px', whiteSpace: "nowrap" }}>영수증재발행(PDF용)</Button></Box><Box sx={{ display: hook.isVisible_btnEstimate ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnEstimate_OnClick} sx={{ width: '144px', height: '24px', whiteSpace: "nowrap" }}>작성일자별 계산서발행</Button></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Stack direction="row" alignItems="center" spacing={0.5} sx={{ width: '105px', height: '22px', display: 'flex', alignItems: 'center', ml: '454px' }}>
                    <Typography variant="body2" sx={{ minWidth: 44, bgcolor: '#f5f5f5', p: 0.3, borderRadius: 1 }}>수납액</Typography>
                    <TextField size="small" fullWidth  sx={{ "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" } }} />
                 </Stack></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_btnPosResultList ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnPosResultList_OnClick} sx={{ width: '120px', height: '24px', whiteSpace: "nowrap" }}>결제처리결과조회</Button></Box><Box sx={{ display: hook.isVisible_btnShowVirtualAccount ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnShowVirtualAccount_OnClick} sx={{ width: '81px', height: '24px', whiteSpace: "nowrap" }}>가상계좌보기</Button></Box><Box sx={{ display: hook.isVisible_btnChangeProcDate ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnChangeProcDate_OnClick} sx={{ width: '92px', height: '24px', whiteSpace: "nowrap" }}>처리일자변경</Button></Box><Box sx={{ display: hook.isVisible_btnProcRct ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnProcRct_OnClick} sx={{ width: '92px', height: '24px', whiteSpace: "nowrap" }}>현금영수증처리</Button></Box><Box sx={{ display: hook.isVisible_btnPrintReRct ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnPrintReRct_OnClick} sx={{ width: '92px', height: '24px', whiteSpace: "nowrap" }}>영수증재발행</Button></Box><Box sx={{ display: hook.isVisible_btnPosvath ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnPrintEstimate_OnClick} sx={{ width: '79px', height: '24px', whiteSpace: "nowrap" }}>부가세정보</Button></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "3px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_gdSetlmentHist ? undefined : 'none' }}><Paper sx={{ width: '561px', height: '174px', width: '100%', height: 'auto', minHeight: '174px' }}><DataGridWrapper rows={hook.ds_oSetlmentHist} columns={columns_gdSetlmentHist} /></Paper></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_btnTraingJubsuinfo ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnTraingJubsuInfo_OnClick} sx={{ width: '158px', height: '24px', whiteSpace: "nowrap" }}>개인접수정보 상세보기</Button></Box><Box sx={{ display: hook.isVisible_lbJubsuHist ? undefined : 'none' }}><Box sx={{ display: "flex", alignItems: "center", width: '120px', height: '22px' }}><Typography variant="body2">개인접수회차이력</Typography></Box></Box><Stack direction="row" alignItems="center" spacing={0.5} sx={{ width: '117px', height: '22px', display: 'flex', alignItems: 'center', ml: '25px' }}>
                    <Typography variant="body2" sx={{ minWidth: 55, bgcolor: '#f5f5f5', p: 0.3, borderRadius: 1 }}>TJMGNO</Typography>
                    <TextField size="small" fullWidth value={hook.ds_ioTrainingJubsu?.TJMGNO || ''} sx={{ "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" } }} />
                 </Stack><Stack direction="row" alignItems="center" spacing={0.5} sx={{ width: '121px', height: '22px', display: 'flex', alignItems: 'center', ml: '3px' }}>
                    <Typography variant="body2" sx={{ minWidth: 60, bgcolor: '#f5f5f5', p: 0.3, borderRadius: 1 }}>TPMGNO</Typography>
                    <TextField size="small" fullWidth value={hook.ds_ioTrainingJubsu?.TPMGNO || ''} sx={{ "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" } }} />
                 </Stack></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "4px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_gdJubsuInfo ? undefined : 'none' }}><Paper sx={{ width: '492px', height: '150px', width: '100%', height: 'auto', minHeight: '150px' }}><DataGridWrapper rows={hook.ds_oJubsuAllInfo} columns={columns_gdJubsuInfo} /></Paper></Box><Box sx={{ display: hook.isVisible_gdOrderHist ? undefined : 'none' }}><Paper sx={{ width: '512px', height: '150px', width: '100%', height: 'auto', minHeight: '150px' }}><DataGridWrapper rows={hook.ds_oOrderHist} columns={columns_gdOrderHist} /></Paper></Box></Stack>

                    </Paper>
                </Grid>
</Grid>

        </PageContainer>
    );
};
export default Frmtraining0020MTrainingJubsuManagement;

function CustomTabPanel(props) {
  const { children, value, index, ...other } = props;

  return (
    <div
      role="tabpanel"
      hidden={value !== index}
      id={`simple-tabpanel-${index}`}
      aria-labelledby={`simple-tab-${index}`}
      {...other}
    >
      {value === index && (
        <Box sx={{ p: 3 }}>
          {children}
        </Box>
      )}
    </div>
  );
}