// @ts-nocheck
import React, { useState } from 'react';
import { Box, Button, Checkbox, Dialog, DialogActions, DialogContent, DialogTitle, FormControl, FormControlLabel, Grid, IconButton, MenuItem, Paper, Radio, RadioGroup, Select, Stack, Tab, Tabs, TextField, Tooltip, Typography } from '@mui/material';
import { DatePicker } from '@mui/x-date-pickers/DatePicker';
import { Add, Check, Close, ContentCopy, Delete, Description, FilterList, Help, Print, Refresh, Save, Search, Sort, TouchApp, Visibility, ZoomIn } from '@mui/icons-material';
import DataGridWrapper from '../../components/DataGridWrapper';
import MultiDataGridWrapper from '../../components/MultiDataGridWrapper';
import DoubleClickDatePicker from '../../components/DoubleClickDatePicker';
import PageContainer from '../../components/PageContainer';
import { useFrmTrainingStat0070 } from './useFrmTrainingStat0070';
import * as FrmTrainingStat0070Data from './FrmTrainingStat0070Data';

export const FrmTrainingStat0070 = () => {
    const hook = useFrmTrainingStat0070();
    const [tabValue_TAB_Training, setTabValue_TAB_Training] = useState(0);
    const columns_gdList = [
        { field: 'GTDEPTNM', headerName: '지부', width: 60 },
        { field: 'col_1', headerName: '구분', width: 41, renderCell: (params) => <Stack spacing={0} sx={{ height: "100%", justifyContent: "center" }}><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>계</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>정규</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>특별</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>교직특별</Box></Stack>, sortable: false },
        { field: 'col_2', headerName: '', width: 58, renderCell: (params) => <Stack spacing={0} sx={{ height: "100%", justifyContent: "center" }}><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>교육횟수</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>금액</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>교육횟수</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>금액</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>교육횟수</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>금액</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>교육횟수</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>금액</Box></Stack>, sortable: false },
        { field: 'BCEDCTSUM', headerName: '총계', width: 81, renderCell: (params) => <Stack spacing={0} sx={{ height: "100%", justifyContent: "center" }}><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.BCEDCTSUM}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.BCATSUM}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.BCRREDCTSUM}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.BCRRATSUM}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.BCSLEDCTSUM}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.BCSLATSUM}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.BCTHSLEDCTSUM}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.BCTHSLATSUM}</Box></Stack>, sortable: false },
        { field: 'PCFENEDCTSUM', headerName: '소방안전관리자 공공(소집)', width: 65, renderCell: (params) => <Stack spacing={0} sx={{ height: "100%", justifyContent: "center" }}><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.PCFENEDCTSUM}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.PCFENATSUM}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.PCFENRREDCT}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.PCFENRRAT}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.PCFENSLEDCT}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.PCFENSLAT}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.PCFENTHSLEDCT}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.PCFENTHSLAT}</Box></Stack>, sortable: false },
        { field: 'PCFECEDCTSUM', headerName: '공공(혼합)', width: 65, renderCell: (params) => <Stack spacing={0} sx={{ height: "100%", justifyContent: "center" }}><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.PCFECEDCTSUM}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.PCFECATSUM}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.PCFECRREDCT}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.PCFECRRAT}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.PCFECSLEDCT}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.PCFECSLAT}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.PCFECTHSLEDCT}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.PCFECTHSLAT}</Box></Stack>, sortable: false },
        { field: 'SGFEEDCTSUM', headerName: '특급', width: 65, renderCell: (params) => <Stack spacing={0} sx={{ height: "100%", justifyContent: "center" }}><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.SGFEEDCTSUM}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.SGFEATSUM}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.SGFERREDCT}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.SGFERRAT}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.SGFESLEDCT}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.SGFESLAT}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.SGFETHSLEDCT}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.SGFETHSLAT}</Box></Stack>, sortable: false },
        { field: 'FTFEEDCTSUM', headerName: '1급', width: 65, renderCell: (params) => <Stack spacing={0} sx={{ height: "100%", justifyContent: "center" }}><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.FTFEEDCTSUM}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.FTFEATSUM}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.FTFERREDCT}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.FTFERRAT}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.FTFESLEDCT}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.FTFESLAT}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.FTFETHSLEDCT}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.FTFETHSLAT}</Box></Stack>, sortable: false },
        { field: 'SDFEEDCTSUM', headerName: '2급정규', width: 65, renderCell: (params) => <Stack spacing={0} sx={{ height: "100%", justifyContent: "center" }}><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.SDFEEDCTSUM}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.SDFEATSUM}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.SDFERREDCT}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.SDFERRAT}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.SDFESLEDCT}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.SDFESLAT}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.SDFETHSLEDCT}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.SDFETHSLAT}</Box></Stack>, sortable: false },
        { field: 'SDFEMUNJEEDCTSUM', headerName: '2급면제', width: 65, renderCell: (params) => <Stack spacing={0} sx={{ height: "100%", justifyContent: "center" }}><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.SDFEMUNJEEDCTSUM}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.SDFEMUNJEATSUM}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.SDFEMUNJERREDCT}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.SDFEMUNJERRAT}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.SDFEMUNJESLEDCT}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.SDFEMUNJESLAT}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.SDFEMUNJETHSLEDCT}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.SDFEMUNJETHSLAT}</Box></Stack>, sortable: false },
        { field: 'TDFEEDCTSUM', headerName: '3급', width: 65, renderCell: (params) => <Stack spacing={0} sx={{ height: "100%", justifyContent: "center" }}><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.TDFEEDCTSUM}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.TDFEATSUM}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.TDFERREDCT}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.TDFERRAT}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.TDFESLEDCT}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.TDFESLAT}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.TDFETHSLEDCT}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.TDFETHSLAT}</Box></Stack>, sortable: false },
        { field: 'DSSEEDCTSUM', headerName: '위험물 안전관리자', width: 65, renderCell: (params) => <Stack spacing={0} sx={{ height: "100%", justifyContent: "center" }}><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.DSSEEDCTSUM}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.DSSEATSUM}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.DSSERREDCT}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.DSSERRAT}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.DSSESLEDCT}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.DSSESLAT}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.DSSETHSLEDCT}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.DSSETHSLAT}</Box></Stack>, sortable: false },
        { field: 'DSCREDCTSUM', headerName: '운송자', width: 65, renderCell: (params) => <Stack spacing={0} sx={{ height: "100%", justifyContent: "center" }}><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.DSCREDCTSUM}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.DSCRATSUM}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.DSCRRREDCT}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.DSCRRRAT}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.DSCRSLEDCT}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.DSCRSLAT}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.DSCRTHSLEDCT}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.DSCRTHSLAT}</Box></Stack>, sortable: false },
        { field: 'DSUYEDCTSUM', headerName: '통합자', width: 65, renderCell: (params) => <Stack spacing={0} sx={{ height: "100%", justifyContent: "center" }}><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.DSUYEDCTSUM}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.DSUYATSUM}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.DSUYRREDCT}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.DSUYRRAT}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.DSUYSLEDCT}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.DSUYSLAT}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.DSUYTHSLEDCT}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.DSUYTHSLAT}</Box></Stack>, sortable: false },
        { field: 'DSTPEDCTSUM', headerName: '운반자', width: 65, renderCell: (params) => <Stack spacing={0} sx={{ height: "100%", justifyContent: "center" }}><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.DSTPEDCTSUM}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.DSTPATSUM}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.DSTPRREDCT}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.DSTPRRAT}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.DSTPSLEDCT}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.DSTPSLAT}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.DSTPTHSLEDCT}</Box><Box sx={{ height: "20px", display: "flex", alignItems: "center" }}>{params.row.DSTPTHSLAT}</Box></Stack>, sortable: false },
    ];
    return (
        <PageContainer>

            <Stack direction="row" alignItems="center" justifyContent="space-between" mb={2}>
                <Typography variant="h5">강습수수료 현황</Typography>
                <Stack direction="row" spacing={1}>
                    
                </Stack>
            </Stack>
<Grid container spacing={2}>

                <Grid item xs={12} md={12}>
                    <Paper sx={{ p: 2, height: '100%' }}>
                        
                        <Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "48px", py: 0.5, width: "100%" }}><Stack direction="row" alignItems="center" spacing={0.5} sx={{ width: '164px', height: '27px', display: 'flex', alignItems: 'center', ml: '20px' }}>
                    <Typography variant="body2" sx={{ minWidth: 56, bgcolor: '#f5f5f5', p: 0.3, borderRadius: 1 }}>조회일자</Typography>
                    <DoubleClickDatePicker sx={{ width: "102px", "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 0px", fontSize: "12px", marginLeft: "-2px" } }} />
                 </Stack><Stack direction="row" alignItems="center" spacing={0.5} sx={{ width: '126px', height: '27px', display: 'flex', alignItems: 'center', ml: '5px' }}>
                    <Typography variant="body2" sx={{ minWidth: 11, bgcolor: '#f5f5f5', p: 0.3, borderRadius: 1 }}>~</Typography>
                    <DoubleClickDatePicker sx={{ width: "102px", "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 0px", fontSize: "12px", marginLeft: "-2px" } }} />
                 </Stack><Box sx={{ display: hook.isVisible_Button0_2 ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnSearch_OnClick} sx={{ width: '37px', height: '24px', whiteSpace: "nowrap" }}>검색</Button></Box><Box sx={{ display: hook.isVisible_btnExcell ? undefined : 'none' }}><Button variant="contained" color="success"  onClick={hook.btnExcell_OnClick} sx={{ width: '53px', height: '24px', whiteSpace: "nowrap" }}>엑셀</Button></Box><Box sx={{ display: hook.isVisible_btnPrint ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnPrint_OnClick} sx={{ width: '65px', height: '24px', whiteSpace: "nowrap" }}>출력</Button></Box><Box sx={{ display: hook.isVisible_btnPrintChart ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnPrintChart_OnClick} sx={{ width: '55px', height: '24px', whiteSpace: "nowrap" }}>화면인쇄</Button></Box><Box sx={{ display: hook.isVisible_btnPrintWarmun ? undefined : 'none' }}><Button variant="contained"   onClick={hook.btnPrintWarmun_OnClick} sx={{ width: '55px', height: '24px', whiteSpace: "nowrap" }}>화면인쇄</Button></Box><Box sx={{ display: hook.isVisible_btnClose ? undefined : 'none' }}><Button variant="contained"   onClick={hook.lfn_End} sx={{ width: '55px', height: '24px', whiteSpace: "nowrap" }}>화면인쇄</Button></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "12px", py: 0.5, width: "100%" }}><Box sx={{ ml: "8px", minWidth: "760px" }}><Box sx={{ display: hook.isVisible_TAB_Training ? undefined : 'none' }}><Box sx={{ width: '760px', height: '723px', width: "100%", height: "auto", minHeight: "723px" }}><Box sx={{ borderBottom: 1, borderColor: "divider" }}><Tabs value={tabValue_TAB_Training} onChange={(e, v) => setTabValue_TAB_Training(v)} aria-label="TAB_Training"><Tab label="    현    황    " /><Tab label="    Chart    " /></Tabs></Box><CustomTabPanel value={tabValue_TAB_Training} index={0}><Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "10px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_gdList ? undefined : 'none' }}><Paper sx={{ width: '753px', height: '688px', width: '100%', height: 'auto', minHeight: '688px' }}><MultiDataGridWrapper rows={hook.ds_exampass} columns={columns_gdList} rowHeight={160} headerHeight={40} hideFooter={true} /></Paper></Box></Stack>
</CustomTabPanel><CustomTabPanel value={tabValue_TAB_Training} index={1}><Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_XChart2 ? undefined : 'none' }}><Box sx={{ width: '432px', height: '338px', border: '1px dashed grey' }}>Unknown: XChart</Box></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_XChart0 ? undefined : 'none' }}><Box sx={{ width: '416px', height: '306px', border: '1px dashed grey' }}>Unknown: XChart</Box></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "2px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_Button0 ? undefined : 'none' }}><Button variant="contained"    sx={{ width: '50px', height: '22px', whiteSpace: "nowrap" }}>직능</Button></Box><Box sx={{ display: hook.isVisible_cbxBang ? undefined : 'none' }}><FormControl size="small" fullWidth sx={{ width: '106px', height: '22px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiSelect-select": { padding: "4px 6px !important" }, bgcolor: "#fff" }}><Select  displayEmpty><MenuItem value=""><em>선택</em></MenuItem>{ (FrmTrainingStat0070Data.ds_ds_Bang || []).map(opt => <MenuItem key={opt.CD} value={opt.CD}>{opt.DATA}</MenuItem>) }</Select></FormControl></Box><Box sx={{ display: hook.isVisible_Button1 ? undefined : 'none' }}><Button variant="contained"    sx={{ width: '50px', height: '22px', whiteSpace: "nowrap" }}>지부</Button></Box><Box sx={{ display: hook.isVisible_cbxJibu ? undefined : 'none' }}><FormControl size="small" fullWidth sx={{ width: '83px', height: '22px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiSelect-select": { padding: "4px 6px !important" }, bgcolor: "#fff" }}><Select  displayEmpty><MenuItem value=""><em>선택</em></MenuItem>{ (FrmTrainingStat0070Data.ds_ds_Jibu || []).map(opt => <MenuItem key={opt.CD} value={opt.CD}>{opt.DATA}</MenuItem>) }</Select></FormControl></Box></Stack>
<Stack direction="row" alignItems="center" spacing={0} sx={{ mt: "187px", py: 0.5, width: "100%" }}><Box sx={{ display: hook.isVisible_XChart1 ? undefined : 'none' }}><Box sx={{ width: '760px', height: '432px', border: '1px dashed grey' }}>Unknown: XChart</Box></Box></Stack>
</CustomTabPanel></Box></Box><Box sx={{ display: hook.isVisible_StartDate ? undefined : 'none' }}><TextField size="small" fullWidth  sx={{ width: '76px', height: '14px', "& .MuiOutlinedInput-notchedOutline": { borderColor: "rgba(0,0,0,0.4)" }, "& .MuiInputBase-input": { padding: "4px 6px" }, bgcolor: "#fff" }} /></Box><Box sx={{ display: hook.isVisible_Static2 ? undefined : 'none' }}><Box sx={{ display: "flex", alignItems: "center", width: '88px', height: '22px' }}><Typography variant="body2">[단위 : 천원]</Typography></Box></Box></Box></Stack>

                    </Paper>
                </Grid>
</Grid>

        </PageContainer>
    );
};
export default FrmTrainingStat0070;

function CustomTabPanel(props) {
  const { children, value, index, ...other } = props;

  return (
    <div
      role="tabpanel"
      hidden={value !== index}
      id={`simple-tabpanel-${index}`}
      aria-labelledby={`simple-tab-${index}`}
      {...other}
    >
      {value === index && (
        <Box sx={{ p: 3 }}>
          {children}
        </Box>
      )}
    </div>
  );
}